const string = { type: 'string', minLength: 1 }
const id = { ...string, pattern: '^ai-' }
const confidence = { type: 'string', enum: ['high', 'medium', 'low'] }
const base = { id, confidence }
const blocks = [
  { type: 'object', properties: { ...base, type: { const: 'heading' }, text: string }, required: ['id', 'type', 'text', 'confidence'], additionalProperties: false },
  { type: 'object', properties: { ...base, type: { const: 'paragraph' }, text: string }, required: ['id', 'type', 'text', 'confidence'], additionalProperties: false },
  { type: 'object', properties: { ...base, type: { enum: ['key_point', 'warning'] }, title: string, text: string }, required: ['id', 'type', 'title', 'text', 'confidence'], additionalProperties: false },
  { type: 'object', properties: { ...base, type: { enum: ['bullet_list', 'checklist'] }, title: string, items: { type: 'array', minItems: 1, items: string } }, required: ['id', 'type', 'title', 'items', 'confidence'], additionalProperties: false },
  { type: 'object', properties: { ...base, type: { const: 'sorting' }, prompt: string, items: { type: 'array', minItems: 2, items: string }, feedback: string }, required: ['id', 'type', 'prompt', 'items', 'feedback', 'confidence'], additionalProperties: false },
  { type: 'object', properties: { ...base, type: { const: 'flashcard' }, title: string, cards: { type: 'array', minItems: 1, items: { type: 'object', properties: { id, front: string, back: string }, required: ['id', 'front', 'back'], additionalProperties: false } } }, required: ['id', 'type', 'title', 'cards', 'confidence'], additionalProperties: false },
  { type: 'object', properties: { ...base, type: { const: 'quick_question' }, question: string, options: { type: 'array', minItems: 2, items: { type: 'object', properties: { id, text: string, correct: { type: 'boolean' }, feedback: string }, required: ['id', 'text', 'correct', 'feedback'], additionalProperties: false } }, explanation: string }, required: ['id', 'type', 'question', 'options', 'explanation', 'confidence'], additionalProperties: false },
  { type: 'object', properties: { ...base, type: { const: 'scenario' }, context: string, customerQuote: string, options: { type: 'array', minItems: 2, items: { type: 'object', properties: { id, text: string, feedback: string, recommended: { type: 'boolean' } }, required: ['id', 'text', 'feedback', 'recommended'], additionalProperties: false } }, explanation: string }, required: ['id', 'type', 'context', 'customerQuote', 'options', 'explanation', 'confidence'], additionalProperties: false },
]

export const courseDraftSchema = { type: 'object', properties: {
  id, sourceDocumentId: string, preset: { type: 'string', enum: ['product', 'sales', 'campaign'] }, title: string, shortDescription: string, longDescription: string, category: string, audience: string, learningObjectives: { type: 'array', minItems: 1, items: string }, estimatedDuration: { type: 'number', minimum: 1 },
  modules: { type: 'array', minItems: 1, items: { type: 'object', properties: { id, title: string, confidence, lessons: { type: 'array', minItems: 1, items: { type: 'object', properties: { id, title: string, confidence, blocks: { type: 'array', minItems: 1, items: { anyOf: blocks } } }, required: ['id', 'title', 'confidence', 'blocks'], additionalProperties: false } } }, required: ['id', 'title', 'confidence', 'lessons'], additionalProperties: false } },
  quiz: { type: 'object', properties: { passScore: { type: 'number', minimum: 0, maximum: 100 }, questions: { type: 'array', minItems: 1, items: { type: 'object', properties: { id, type: { type: 'string', enum: ['multiple_choice', 'true_false', 'multi_select'] }, prompt: string, options: { type: 'array', minItems: 2, items: { type: 'object', properties: { id, text: string }, required: ['id', 'text'], additionalProperties: false } }, correctOptionIndexes: { type: 'array', minItems: 1, items: { type: 'integer', minimum: 0 } }, explanation: string, points: { type: 'number', minimum: 1 } }, required: ['id', 'type', 'prompt', 'options', 'correctOptionIndexes', 'explanation', 'points'], additionalProperties: false } } }, required: ['passScore', 'questions'], additionalProperties: false },
  xp: { type: 'object', properties: { lesson: { type: 'number' }, quiz: { type: 'number' }, course: { type: 'number' } }, required: ['lesson', 'quiz', 'course'], additionalProperties: false }, badge: { type: 'object', properties: { id, name: string, description: string, condition: { const: 'course_complete' } }, required: ['id', 'name', 'description', 'condition'], additionalProperties: false }, warnings: { type: 'array', items: { type: 'object', properties: { id, code: { type: 'string', enum: ['source_short', 'objective_unclear', 'quiz_insufficient', 'empty_lesson', 'quiz_invalid', 'trainer_verification', 'time_sensitive'] }, message: string, reviewed: { type: 'boolean' } }, required: ['id', 'code', 'message', 'reviewed'], additionalProperties: false } }, confidence, createdAt: string, updatedAt: string, status: { const: 'needs_review' },
}, required: ['id', 'sourceDocumentId', 'preset', 'title', 'shortDescription', 'longDescription', 'category', 'audience', 'learningObjectives', 'estimatedDuration', 'modules', 'quiz', 'xp', 'badge', 'warnings', 'confidence', 'createdAt', 'updatedAt', 'status'], additionalProperties: false }

export const regenerateSchema = { type: 'object', properties: { after: string }, required: ['after'], additionalProperties: false }
