import { describe, expect, it } from 'vitest'
import { ContentService, CONTENT_STORAGE_KEY, createBlock, createCourse, createLesson, createModule, duplicateBlock, duplicateLesson, duplicateModule, validateCourseForPublish, type StorageLike } from '../services/contentService'
import { createDefaultProgress, rewardLessonCompletion, rewardQuizPass } from '../services/progressService'
import { gradeQuiz } from '../utils/quiz'

function memoryStorage(seed?: string): StorageLike { const values = new Map<string, string>(); if (seed !== undefined) values.set(CONTENT_STORAGE_KEY, seed); return { getItem: (key) => values.get(key) ?? null, setItem: (key, value) => { values.set(key, value) }, removeItem: (key) => { values.delete(key) } } }

describe('ContentService CMS MVP', () => {
  it('creates a course, module, lesson and block then publishes it', () => {
    const service = new ContentService(memoryStorage()); const course = createCourse('Pilot'); const module = createModule('Module 1'); const lesson = createLesson('Lesson 1'); lesson.blocks.push(createBlock('paragraph')); module.lessons.push(lesson); course.modules.push(module)
    service.addCourse(course); service.setPublishStatus(course.id, 'published')
    expect(service.getCourse(course.id, 'trainer')?.modules[0].lessons[0].blocks).toHaveLength(1)
    expect(service.getCourses('employee').some((item) => item.id === course.id)).toBe(true)
  })
  it('provides the complete pilot seed only when storage is empty', () => { const storage = memoryStorage(); const service = new ContentService(storage); const pilot = service.getCourse('mac-back-to-school', 'trainer'); expect(pilot?.modules).toHaveLength(4); expect(pilot?.modules.flatMap((module) => module.lessons)).toHaveLength(8); expect(pilot?.modules.flatMap((module) => module.lessons).filter((lesson) => lesson.required)).toHaveLength(7); expect(pilot?.quiz.questions).toHaveLength(10); expect(pilot?.quiz.passScore).toBe(80); const blockTypes = new Set(pilot?.modules.flatMap((module) => module.lessons).flatMap((lesson) => lesson.blocks).map((block) => block.type)); expect([...blockTypes]).toEqual(expect.arrayContaining(['heading', 'paragraph', 'image', 'video', 'flashcard', 'quick_question', 'scenario'])); const custom = { ...service.getStore(), courses: [createCourse('Nội dung đang có')] }; storage.setItem(CONTENT_STORAGE_KEY, JSON.stringify(custom)); expect(new ContentService(storage).getCourses('trainer').map((course) => course.title)).toEqual(['Nội dung đang có']) })
  it('keeps draft courses hidden from employees', () => { const service = new ContentService(memoryStorage()); const course = createCourse('Draft only'); service.addCourse(course); expect(service.getCourses('employee').some((item) => item.id === course.id)).toBe(false); expect(service.getCourses('trainer').some((item) => item.id === course.id)).toBe(true) })
  it('upserts one course without replacing existing content', () => { const service = new ContentService(memoryStorage()); const existing = service.getCourses('trainer')[0]; const course = createCourse('Pilot mới'); service.upsertCourse(course); service.upsertCourse({ ...course, description: 'Đã cập nhật' }); expect(service.getCourses('trainer')).toHaveLength(2); expect(service.getCourse(existing.id, 'trainer')).toEqual(existing); expect(service.getCourse(course.id, 'trainer')?.description).toBe('Đã cập nhật') })
  it('keeps a published course available after a storage reload', () => { const storage = memoryStorage(); const service = new ContentService(storage); const course = createCourse('Published after refresh'); course.publishStatus = 'published'; service.upsertCourse(course); expect(new ContentService(storage).getCourse(course.id, 'employee')?.title).toBe('Published after refresh') })
  it('reorders blocks without data loss', () => { const first = createBlock('heading'); const second = createBlock('paragraph'); const reordered = [first, second]; [reordered[0], reordered[1]] = [reordered[1], reordered[0]]; expect(reordered.map((item) => item.id)).toEqual([second.id, first.id]) })
  it('exports and imports valid JSON', () => { const source = new ContentService(memoryStorage()); const course = createCourse('Export me'); source.addCourse(course); const target = new ContentService(memoryStorage()); target.importJson(source.exportCourse(course.id), 'overwrite'); expect(target.getCourse(course.id, 'trainer')?.title).toBe('Export me') })
  it('does not mutate content when import JSON is invalid', () => { const service = new ContentService(memoryStorage()); const before = service.exportAll(); expect(() => service.importJson('{broken', 'overwrite')).toThrow(); expect(service.exportAll()).toBe(before) })
  it('recovers from corrupted localStorage without crashing', () => { const service = new ContentService(memoryStorage('{broken')); expect(service.getCourses('employee')).toHaveLength(1); expect(service.getWarning()).toContain('Không thể đọc') })
  it('blocks publishing incomplete content with actionable issues', () => { const course = createCourse(''); course.quiz.passScore = 101; const issues = validateCourseForPublish(course); expect(issues.map((issue) => issue.id)).toEqual(expect.arrayContaining(['course-title', 'course-modules', 'quiz-empty', 'quiz-pass-score'])) })
  it('accepts the complete seeded course for publishing', () => { const course = new ContentService(memoryStorage()).getCourses('trainer')[0]; expect(validateCourseForPublish(course)).toEqual([]) })
  it('duplicates the complete hierarchy with new IDs and draft status', () => { const service = new ContentService(memoryStorage()); const original = service.getCourses('trainer')[0]; const duplicate = service.duplicateCourse(original.id); expect(duplicate?.publishStatus).toBe('draft'); expect(duplicate?.id).not.toBe(original.id); expect(duplicate?.quiz.id).not.toBe(original.quiz.id); expect(duplicate?.modules[0].id).not.toBe(original.modules[0].id); expect(duplicate?.modules[0].lessons[0].id).not.toBe(original.modules[0].lessons[0].id); expect(duplicate?.modules[0].lessons[0].blocks[0].id).not.toBe(original.modules[0].lessons[0].blocks[0].id); expect(duplicate?.quiz.questions[0].id).not.toBe(original.quiz.questions[0].id) })
  it('duplicates modules, lessons and nested blocks with fresh IDs', () => { const course = new ContentService(memoryStorage()).getCourses('trainer')[0]; const originalLesson = course.modules[0].lessons[1]; const originalScenario = originalLesson.blocks.find((item) => item.type === 'scenario'); expect(originalScenario?.type).toBe('scenario'); if (!originalScenario || originalScenario.type !== 'scenario') return; const module = duplicateModule(course.modules[0]); const lesson = duplicateLesson(originalLesson); const block = duplicateBlock(originalScenario); expect(module.id).not.toBe(course.modules[0].id); expect(module.lessons[1].id).not.toBe(originalLesson.id); expect(module.lessons[1].blocks[0].id).not.toBe(originalLesson.blocks[0].id); expect(lesson.blocks[0].id).not.toBe(originalLesson.blocks[0].id); expect(block.id).not.toBe(originalScenario.id); if (block.type === 'scenario') expect(block.options[0].id).not.toBe(originalScenario.options[0].id) })
  it('validates description, duration, answer count and badge content', () => { const course = createCourse('Pilot'); course.modules = [{ ...createModule(), lessons: [{ ...createLesson(), blocks: [createBlock('paragraph')] }] }]; course.quiz.questions = [{ id: 'q', type: 'multiple_choice', prompt: 'Câu hỏi', options: ['Một'], correctOptionIndex: 0, correctOptionIndexes: [0], explanation: '', relatedLessonId: '', relatedModuleId: '', points: 1 }]; course.gamification.badges = [{ id: 'b', name: '', description: '', condition: 'course_complete' }]; course.durationMinutes = 0; expect(validateCourseForPublish(course).map((issue) => issue.id)).toEqual(expect.arrayContaining(['course-description', 'course-duration', 'question-q-options', 'badge-b'])) })
  it('does not mutate in-memory content when storage write fails', () => { const storage = memoryStorage(); const service = new ContentService(storage); const before = service.exportAll(); storage.setItem = () => { throw new Error('quota') }; expect(() => service.addCourse(createCourse('Fail'))).toThrow('quota'); expect(service.exportAll()).toBe(before) })
})

describe('gamification', () => {
  it('awards lesson and completed-module XP only once', () => { const course = new ContentService(memoryStorage()).getCourses('employee')[0]; const firstLesson = course.modules[0].lessons[0]; const lastModuleLesson = course.modules[0].lessons[1]; const base = { ...createDefaultProgress(), completedLessonIds: [firstLesson.id] }; const firstReward = rewardLessonCompletion(base, course, firstLesson.id); const duplicatedFirstReward = rewardLessonCompletion(firstReward, course, firstLesson.id); expect(duplicatedFirstReward.totalXp).toBe(firstLesson.xpReward); const completedModule = rewardLessonCompletion({ ...duplicatedFirstReward, completedLessonIds: [firstLesson.id, lastModuleLesson.id] }, course, lastModuleLesson.id); const duplicatedModuleReward = rewardLessonCompletion(completedModule, course, lastModuleLesson.id); expect(duplicatedModuleReward.totalXp).toBe(firstLesson.xpReward + lastModuleLesson.xpReward + course.modules[0].xpReward); expect(duplicatedModuleReward.earnedBadgeIds).toEqual(expect.arrayContaining(['badge-first-lesson', 'badge-module'])) })
  it('awards quiz XP and badges only after required lessons and only once', () => { const course = new ContentService(memoryStorage()).getCourses('employee')[0]; const answers = Object.fromEntries(course.quiz.questions.map((question) => [question.id, question.correctOptionIndex])); const result = gradeQuiz(course.id, course.quiz.questions, answers, 1); const required = course.modules.flatMap((module) => module.lessons).filter((lesson) => lesson.required).map((lesson) => lesson.id); expect(rewardQuizPass(createDefaultProgress(), course, result).totalXp).toBe(0); const once = rewardQuizPass({ ...createDefaultProgress(), completedLessonIds: required }, course, result); const twice = rewardQuizPass(once, course, result); expect(twice.totalXp).toBe(course.quiz.xpReward + course.gamification.courseCompletionXp); expect(twice.earnedBadgeIds).toEqual(expect.arrayContaining(['badge-quiz', 'badge-course'])) })
})
