import { ChevronDown, ChevronUp, Copy, Eye, EyeOff, Plus, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { LessonBlockRenderer } from '../lesson/LessonBlockRenderer'
import { createBlock } from '../../services/contentService'
import type { LessonBlock } from '../../types'

const groups: Array<{ label: string; types: LessonBlock['type'][] }> = [
  { label: 'Nội dung', types: ['heading', 'paragraph', 'image', 'video', 'bullet_list', 'quote', 'divider', 'key_point', 'warning', 'attachment'] },
  { label: 'Tương tác', types: ['quick_question', 'true_false', 'multiple_choice', 'multi_select', 'flashcard', 'checklist', 'scenario', 'dialogue', 'sorting', 'matching'] },
  { label: 'Gamification', types: ['xp_reward', 'badge_reward', 'completion_message', 'module_challenge', 'unlock_condition'] },
]
const labels: Record<LessonBlock['type'], string> = { heading: 'Tiêu đề', paragraph: 'Đoạn văn', image: 'Hình ảnh', video: 'Video', bullet_list: 'Danh sách', quote: 'Trích dẫn', divider: 'Đường phân cách', key_point: 'Điểm cần nhớ', warning: 'Cảnh báo', attachment: 'Tài liệu', quick_question: 'Câu hỏi nhanh', true_false: 'Đúng / Sai', multiple_choice: 'Một lựa chọn', multi_select: 'Nhiều lựa chọn', flashcard: 'Flashcard', checklist: 'Checklist', scenario: 'Tình huống', dialogue: 'Hội thoại', sorting: 'Sắp xếp', matching: 'Ghép cặp · Experimental', xp_reward: 'XP reward', badge_reward: 'Badge reward', completion_message: 'Lời chúc mừng', module_challenge: 'Thử thách module', unlock_condition: 'Điều kiện mở khóa' }
const lines = (value: string) => value.split('\n').map((item) => item.trim()).filter(Boolean)

function Field({ label, value, onChange, area = false, type = 'text' }: { label: string; value: string | number; onChange(value: string): void; area?: boolean; type?: string }) { return <label className="cms-field"><span>{label}</span>{area ? <textarea value={value} onChange={(event) => onChange(event.target.value)} /> : <input type={type} value={value} onChange={(event) => onChange(event.target.value)} />}</label> }
function BlockFields({ block, update }: { block: LessonBlock; update(next: LessonBlock): void }) {
  const set = (values: Partial<LessonBlock>) => update({ ...block, ...values } as LessonBlock)
  if (block.type === 'divider') return <p className="muted">Block không có nội dung chỉnh sửa.</p>
  if (block.type === 'heading') return <><Field label="Tiêu đề" value={block.text} onChange={(text) => set({ text })} /><label className="cms-field"><span>Cấp heading</span><select value={block.level} onChange={(event) => set({ level: Number(event.target.value) as 2 | 3 })}><option value="2">Heading 2</option><option value="3">Heading 3</option></select></label></>
  if (block.type === 'paragraph') return <Field label="Nội dung" value={block.text} area onChange={(text) => set({ text })} />
  if (block.type === 'image') return <><Field label="Image URL" value={block.url} onChange={(url) => set({ url })} /><Field label="Alt text" value={block.alt} onChange={(alt) => set({ alt })} /><Field label="Chú thích" value={block.caption ?? ''} onChange={(caption) => set({ caption })} /></>
  if (block.type === 'video') return <><Field label="Tiêu đề" value={block.title} onChange={(title) => set({ title })} /><Field label="Video URL (https)" value={block.url} onChange={(url) => set({ url })} /><label className="cms-field"><span>Provider</span><select value={block.provider} onChange={(event) => set({ provider: event.target.value as typeof block.provider })}><option value="youtube">YouTube</option><option value="vimeo">Vimeo</option><option value="direct">Direct URL</option></select></label><Field label="Mô tả" value={block.description} area onChange={(description) => set({ description })} /><Field label="Thời lượng (phút)" type="number" value={block.durationMinutes} onChange={(value) => set({ durationMinutes: Math.max(0, Number(value)) })} /><Field label="Transcript (tùy chọn)" value={block.transcript ?? ''} area onChange={(transcript) => set({ transcript })} /><label className="check-row"><input type="checkbox" checked={block.required} onChange={(event) => set({ required: event.target.checked })} />Bắt buộc xem</label></>
  if (block.type === 'bullet_list') return <><Field label="Tiêu đề" value={block.title} onChange={(title) => set({ title })} /><Field label="Mỗi dòng là một mục" value={block.items.join('\n')} area onChange={(value) => set({ items: lines(value) })} /></>
  if (block.type === 'quote') return <><Field label="Trích dẫn" value={block.text} area onChange={(text) => set({ text })} /><Field label="Nguồn" value={block.attribution ?? ''} onChange={(attribution) => set({ attribution })} /></>
  if (block.type === 'key_point' || block.type === 'warning') return <><Field label="Tiêu đề" value={block.title} onChange={(title) => set({ title })} /><Field label="Nội dung" value={block.text} area onChange={(text) => set({ text })} /></>
  if (block.type === 'attachment') return <><Field label="Tên tài liệu" value={block.title} onChange={(title) => set({ title })} /><Field label="URL" value={block.url} onChange={(url) => set({ url })} /><Field label="Mô tả" value={block.description ?? ''} onChange={(description) => set({ description })} /></>
  if (block.type === 'quick_question' || block.type === 'multiple_choice' || block.type === 'multi_select') return <><Field label="Câu hỏi" value={block.question} area onChange={(question) => set({ question })} /><Field label="Đáp án — thêm * trước đáp án đúng" value={block.options.map((item) => `${item.correct ? '*' : ''}${item.text}`).join('\n')} area onChange={(value) => set({ options: lines(value).slice(0, 4).map((text, index) => ({ id: block.options[index]?.id ?? `option-${index}`, text: text.replace(/^\*/, ''), correct: text.startsWith('*'), feedback: block.options[index]?.feedback ?? '' })) })} /><Field label="Giải thích" value={block.explanation} area onChange={(explanation) => set({ explanation })} /></>
  if (block.type === 'true_false') return <><Field label="Nhận định" value={block.question} area onChange={(question) => set({ question })} /><label className="cms-field"><span>Đáp án đúng</span><select value={String(block.correct)} onChange={(event) => set({ correct: event.target.value === 'true' })}><option value="true">Đúng</option><option value="false">Sai</option></select></label><Field label="Phản hồi đúng" value={block.correctFeedback} onChange={(correctFeedback) => set({ correctFeedback })} /><Field label="Phản hồi sai" value={block.incorrectFeedback} onChange={(incorrectFeedback) => set({ incorrectFeedback })} /><Field label="Giải thích" value={block.explanation} area onChange={(explanation) => set({ explanation })} /></>
  if (block.type === 'flashcard') return <><Field label="Tiêu đề" value={block.title} onChange={(title) => set({ title })} /><Field label="Mỗi dòng: Mặt trước | Mặt sau | Image URL (tùy chọn)" value={block.cards.map((card) => `${card.front} | ${card.back}${card.imageUrl ? ` | ${card.imageUrl}` : ''}`).join('\n')} area onChange={(value) => set({ cards: lines(value).map((line, index) => { const [front = '', back = '', imageUrl = ''] = line.split('|').map((part) => part.trim()); return { id: block.cards[index]?.id ?? `card-${index}`, front, back, imageUrl } }) })} /></>
  if (block.type === 'checklist') return <><Field label="Tiêu đề" value={block.title} onChange={(title) => set({ title })} /><Field label="Mỗi dòng là một mục" value={block.items.map((item) => item.text).join('\n')} area onChange={(value) => set({ items: lines(value).map((text, index) => ({ id: block.items[index]?.id ?? `item-${index}`, text })) })} /></>
  if (block.type === 'scenario') return <><Field label="Bối cảnh" value={block.context} area onChange={(context) => set({ context })} /><Field label="Câu nói khách hàng" value={block.customerQuote} area onChange={(customerQuote) => set({ customerQuote })} /><Field label="Phương án — thêm * trước phương án khuyến nghị" value={block.options.map((item) => `${item.recommended ? '*' : ''}${item.text} | ${item.feedback}`).join('\n')} area onChange={(value) => set({ options: lines(value).slice(0, 4).map((line, index) => { const [rawText = '', feedback = ''] = line.split('|').map((part) => part.trim()); return { id: block.options[index]?.id ?? `option-${index}`, text: rawText.replace(/^\*/, ''), feedback, recommended: rawText.startsWith('*') } }) })} /><Field label="Giải thích" value={block.explanation} area onChange={(explanation) => set({ explanation })} /></>
  if (block.type === 'dialogue') return <><Field label="Tiêu đề" value={block.title} onChange={(title) => set({ title })} /><Field label="Mỗi dòng: Người nói | Nội dung" value={block.lines.map((item) => `${item.speaker} | ${item.text}`).join('\n')} area onChange={(value) => set({ lines: lines(value).map((line) => { const [speaker = '', text = ''] = line.split('|').map((part) => part.trim()); return { speaker, text } }) })} /></>
  if (block.type === 'sorting') return <><Field label="Yêu cầu" value={block.prompt} onChange={(prompt) => set({ prompt })} /><Field label="Thứ tự đúng — mỗi dòng một mục" value={block.items.map((item) => item.text).join('\n')} area onChange={(value) => set({ items: lines(value).map((text, index) => ({ id: block.items[index]?.id ?? `item-${index}`, text })) })} /><Field label="Phản hồi đúng" value={block.feedback} onChange={(feedback) => set({ feedback })} /></>
  if (block.type === 'matching') return <><Field label="Yêu cầu" value={block.prompt} onChange={(prompt) => set({ prompt })} /><Field label="Mỗi dòng: Vế trái | Vế phải" value={block.pairs.map((item) => `${item.left} | ${item.right}`).join('\n')} area onChange={(value) => set({ pairs: lines(value).map((line, index) => { const [left = '', right = ''] = line.split('|').map((part) => part.trim()); return { id: block.pairs[index]?.id ?? `pair-${index}`, left, right } }) })} /><Field label="Phản hồi đúng" value={block.feedback} onChange={(feedback) => set({ feedback })} /></>
  if (block.type === 'xp_reward') return <><Field label="XP" type="number" value={block.amount} onChange={(value) => set({ amount: Number(value) })} /><Field label="Thông báo" value={block.message} onChange={(message) => set({ message })} /></>
  if (block.type === 'badge_reward') return <><Field label="Badge ID" value={block.badgeId} onChange={(badgeId) => set({ badgeId })} /><Field label="Thông báo" value={block.message} onChange={(message) => set({ message })} /></>
  if (block.type === 'completion_message') return <><Field label="Tiêu đề" value={block.title} onChange={(title) => set({ title })} /><Field label="Thông báo" value={block.message} area onChange={(message) => set({ message })} /></>
  if (block.type === 'module_challenge') return <><Field label="Tiêu đề" value={block.title} onChange={(title) => set({ title })} /><Field label="Mô tả" value={block.description} area onChange={(description) => set({ description })} /></>
  if (block.type === 'unlock_condition') return <Field label="Điều kiện" value={block.description} area onChange={(description) => set({ description })} />
  return null
}

export function BlockEditor({ blocks, onChange }: { blocks: LessonBlock[]; onChange(blocks: LessonBlock[]): void }) {
  const [picker, setPicker] = useState(false); const update = (index: number, block: LessonBlock) => onChange(blocks.map((item, i) => i === index ? block : item)); const move = (index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= blocks.length) return; const next = [...blocks]; [next[index], next[target]] = [next[target], next[index]]; onChange(next) }
  return <div className="block-editor"><div className="section-heading compact"><div><span className="overline">Lesson blocks</span><h2>Nội dung tương tác</h2></div><button type="button" className="button button-primary" onClick={() => setPicker(!picker)}><Plus />Thêm block</button></div>{picker && <div className="block-picker">{groups.map((group) => <section key={group.label}><strong>{group.label}</strong><div>{group.types.map((type) => <button key={type} onClick={() => { onChange([...blocks, createBlock(type)]); setPicker(false) }}>{labels[type]}</button>)}</div></section>)}</div>}{blocks.map((block, index) => <article className="cms-block" key={block.id}><header><strong>{labels[block.type]}</strong><span className="cms-block-actions"><button aria-label="Thu gọn block" onClick={() => update(index, { ...block, collapsed: !block.collapsed })}>{block.collapsed ? <Eye /> : <EyeOff />}</button><button aria-label="Di chuyển lên" disabled={index === 0} onClick={() => move(index, -1)}><ChevronUp /></button><button aria-label="Di chuyển xuống" disabled={index === blocks.length - 1} onClick={() => move(index, 1)}><ChevronDown /></button><button aria-label="Duplicate block" onClick={() => onChange([...blocks.slice(0, index + 1), { ...structuredClone(block), id: `${block.id}-copy-${Date.now()}` }, ...blocks.slice(index + 1)])}><Copy /></button><button aria-label="Xóa block" onClick={() => onChange(blocks.filter((_, i) => i !== index))}><Trash2 /></button></span></header>{!block.collapsed && <><div className="cms-block-fields"><BlockFields block={block} update={(next) => update(index, next)} /></div><details className="block-preview"><summary><Eye /> Preview block</summary><div className="lesson-article preview-surface"><LessonBlockRenderer block={block} /></div></details></>}</article>)}{!blocks.length && <div className="empty-product-state"><h3>Lesson chưa có block</h3><p>Chọn “Thêm block” để bắt đầu xây trải nghiệm học.</p></div>}</div>
}
