import { Download, RefreshCcw, Upload } from 'lucide-react'
import { useRef, useState } from 'react'
import { contentService } from '../../services/contentService'
import type { ImportConflictStrategy } from '../../types'

const download = (name: string, text: string) => { const blob = new Blob([text], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url) }
export function ImportExportPanel({ courseId, onChange }: { courseId?: string; onChange(): void }) {
  const input = useRef<HTMLInputElement>(null); const [pending, setPending] = useState(''); const [message, setMessage] = useState(''); const [duplicates, setDuplicates] = useState<string[]>([])
  const inspect = async (file?: File) => { if (!file) return; const text = await file.text(); const preview = contentService.previewImport(text); if (!preview.valid) { setPending(''); setDuplicates([]); setMessage(preview.errors.join(' ')); return } setPending(text); setDuplicates(preview.duplicateIds); setMessage(preview.duplicateIds.length ? `Trùng ID: ${preview.duplicateIds.join(', ')}. Chọn cách xử lý.` : 'File hợp lệ và sẵn sàng import.') }
  const apply = (strategy: ImportConflictStrategy) => { try { contentService.importJson(pending, strategy); setMessage(strategy === 'cancel' ? 'Đã hủy import.' : 'Import thành công.'); setPending(''); setDuplicates([]); if (input.current) input.current.value = ''; onChange() } catch (error) { setMessage(error instanceof Error ? error.message : 'Import thất bại.') } }
  return <section className="import-panel"><h2>Import & Export</h2><p>JSON được validate trước khi thay đổi dữ liệu hiện tại.</p><div className="inline-actions"><button className="button button-secondary" onClick={() => download('fstudio-content.json', contentService.exportAll())}><Download />Export tất cả</button>{courseId && <button className="button button-secondary" onClick={() => download(`${courseId}.json`, contentService.exportCourse(courseId))}><Download />Export course</button>}<button className="button button-secondary" onClick={() => input.current?.click()}><Upload />Chọn JSON</button><input ref={input} hidden type="file" accept="application/json,.json" onChange={(event) => void inspect(event.target.files?.[0])} /></div>{message && <p className={pending ? 'import-message ready' : 'import-message'} role="status">{message}</p>}{pending && <div className="inline-actions">{duplicates.length ? <><button className="button button-primary" onClick={() => apply('overwrite')}>Ghi đè</button><button className="button button-secondary" onClick={() => apply('copy')}>Tạo bản sao</button></> : <button className="button button-primary" onClick={() => apply('overwrite')}>Import</button>}<button className="button button-secondary" onClick={() => apply('cancel')}>Hủy</button></div>}<button className="text-link danger" onClick={() => { if (window.confirm('Reset toàn bộ content về dữ liệu mẫu?')) { contentService.reset(); onChange(); setMessage('Đã khôi phục dữ liệu mẫu.'); } }}><RefreshCcw />Reset content</button></section>
}
