import { Award, Check, ChevronRight, Clock3, LockKeyhole, Play, Sparkles, Users } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { CourseModule } from '../../components/course/CourseModule'
import { ProgressBar } from '../../components/ProgressBar'
import { useCourse } from '../../hooks/useCourse'
import { useLearningProgress } from '../../hooks/useLearningProgress'
import type { LessonStatus } from '../../types'
import { formatDuration } from '../../utils/course'
import { getContinueLesson, isQuizUnlocked } from '../../utils/courseProgress'
import { NotFoundPage } from '../NotFoundPage'
import { Badge } from '../../components/Badge'

export function CourseDetailPage() {
  const { courseId } = useParams(); const { progress } = useLearningProgress(); const course = useCourse(courseId)
  if (!course) return <NotFoundPage />
  const lessons = course.modules.flatMap((module) => module.lessons); const continueLesson = getContinueLesson(course, progress.completedLessonIds, progress.currentLessonId); const quizUnlocked = isQuizUnlocked(course, progress.completedLessonIds)
  const getStatus = (lessonId: string): LessonStatus => { if (progress.completedLessonIds.includes(lessonId)) return 'completed'; if (progress.currentLessonId === lessonId) return 'in_progress'; const index = lessons.findIndex((lesson) => lesson.id === lessonId); const previousComplete = index === 0 || progress.completedLessonIds.includes(lessons[index - 1].id); return previousComplete ? 'not_started' : 'locked' }
  const remainingRequiredLessons = lessons.filter((lesson) => lesson.required && !progress.completedLessonIds.includes(lesson.id)).length
  const totalXp = lessons.reduce((sum, lesson) => sum + lesson.xpReward, 0) + course.modules.reduce((sum, module) => sum + module.xpReward, 0) + course.quiz.xpReward + course.gamification.courseCompletionXp; const completionBadge = course.gamification.badges.find((badge) => badge.condition === 'course_complete')
  return <><section className="course-hero"><div className="container course-hero-grid"><div className="course-cover">{course.coverUrl ? <img src={course.coverUrl} alt={`Ảnh bìa khóa học ${course.title}`} /> : <span><Sparkles />F.Studio Learning</span>}</div><div><div className="breadcrumbs"><Link to="/courses">Khóa học</Link><ChevronRight /><span>Chi tiết</span></div><Badge variant="blue">{course.category}</Badge><h1>{course.title}</h1><p>{course.description}</p>{course.audience && <p className="course-audience"><Users />Dành cho {course.audience}</p>}<div className="course-meta"><span><Clock3 />{formatDuration(course.durationMinutes)}</span><span>{course.modules.length} module</span><span>{lessons.length} bài học</span><Badge variant="neutral">{course.level}</Badge></div><ProgressBar value={course.progress} label="Tiến độ khóa học" />{continueLesson ? <Link className="button button-primary course-cta" to={`/learn/${course.id}/${continueLesson.id}`}><Play size={18} fill="currentColor" />{course.progress ? 'Tiếp tục học' : 'Bắt đầu học'}</Link> : quizUnlocked && <Link className="button button-primary course-cta" to={`/quiz/${course.id}`}>Làm bài kiểm tra</Link>}</div></div></section><section className="section container course-detail-grid"><div><div className="section-heading"><div><span className="ui-eyebrow">Lộ trình</span><h2>Nội dung khóa học</h2></div></div><div className="module-list">{course.modules.map((module, index) => <CourseModule key={module.id} courseId={course.id} module={module} index={index} getStatus={getStatus} />)}</div><div className={`quiz-unlock-card ${quizUnlocked ? 'unlocked' : ''}`}>{quizUnlocked ? <Check /> : <LockKeyhole />}<div><strong>{quizUnlocked ? 'Quiz đã được mở khóa' : 'Quiz cuối khóa đang bị khóa'}</strong><p>{quizUnlocked ? `Điểm đạt: ${course.quiz.passScore}% · ${course.quiz.questions.length} câu hỏi.` : `Hoàn thành ${remainingRequiredLessons} bài học bắt buộc còn lại để mở quiz.`}</p></div>{quizUnlocked && <Link className="button button-primary" to={`/quiz/${course.id}`}>Làm quiz</Link>}</div></div><aside className="course-info-stack"><section className="info-card"><h3>Mục tiêu học tập</h3><ul>{course.objectives.map((objective) => <li key={objective}><Check />{objective}</li>)}</ul></section><section className="reward-summary"><span><Sparkles /></span><div><strong>{totalXp} XP</strong><small>Có thể nhận trong khóa học</small></div></section>{completionBadge && <section className="reward-summary"><span><Award /></span><div><strong>{completionBadge.icon} {completionBadge.name}</strong><small>{completionBadge.description}</small></div></section>}</aside></section></>
}
