import { Award, Bookmark, CalendarDays, CheckCircle2, Clock3, Map, Target, UserRound } from 'lucide-react'
import { Link, useLocation } from 'react-router-dom'
import { ProgressBar } from '../../components/ProgressBar'
import { useLearningProgress } from '../../hooks/useLearningProgress'
import { courseService } from '../../services/courseService'

const pageMeta = {
  '/journey': { eyebrow: 'Lộ trình cá nhân', title: 'Learning Journey', description: 'Một nơi để nhìn lại hành trình và biết bước tiếp theo.' },
  '/progress': { eyebrow: 'Năng lực', title: 'Tiến độ học tập', description: 'Theo dõi mức độ hoàn thành theo nhóm kiến thức.' },
  '/history': { eyebrow: 'Hoạt động', title: 'Lịch sử học tập', description: 'Các bài học, quiz và cột mốc gần đây.' },
  '/profile': { eyebrow: 'Tài khoản', title: 'Hồ sơ cá nhân', description: 'Thông tin công việc và tùy chọn học tập.' },
} as const

export function JourneyPage() {
  const { pathname } = useLocation(); const meta = pageMeta[pathname as keyof typeof pageMeta] ?? pageMeta['/journey']; const { progress } = useLearningProgress(); const user = courseService.getUser(); const courses = courseService.getCourses(progress.completedLessonIds, progress.latestQuizResult); const active = courses[0]
  if (pathname === '/profile') return <section className="page container"><div className="page-heading"><span className="ui-eyebrow">{meta.eyebrow}</span><h1>{meta.title}</h1><p>{meta.description}</p></div><div className="profile-grid"><article className="product-card profile-card"><span className="profile-avatar"><UserRound /></span><div><h2>{user.name}</h2><p>{user.store}</p><span className="badge badge-info">Employee</span></div></article><article className="product-card"><h2>Ưu tiên học tập</h2><div className="preference-row"><span>Nhắc học hằng tuần</span><strong>Thứ Hai · 09:00</strong></div><div className="preference-row"><span>Mục tiêu</span><strong>2 bài / tuần</strong></div><div className="preference-row"><span>Ngôn ngữ</span><strong>Tiếng Việt</strong></div></article></div></section>
  return <section className="page container"><div className="page-heading"><span className="ui-eyebrow">{meta.eyebrow}</span><h1>{meta.title}</h1><p>{meta.description}</p></div><div className="journey-hero product-card"><div><span className="badge badge-mac">Mac</span><h2>{active.title}</h2><p>Bước tiếp theo: tiếp tục bài học gần nhất hoặc hoàn thành quiz cuối khóa.</p><Link className="button button-primary" to={`/courses/${active.id}`}>Tiếp tục hành trình</Link></div><div className="journey-progress"><strong>{active.progress}%</strong><ProgressBar value={active.progress} /></div></div><div className="journey-grid"><article className="product-card"><Target /><h3>Mục tiêu tuần</h3><strong>2 / 3 bài</strong><p>Còn một bài để hoàn thành mục tiêu.</p></article><article className="product-card"><Award /><h3>Thành tích</h3><strong>3 cột mốc</strong><p>Khởi đầu tốt · Học đều · Quiz đầu tiên</p></article><article className="product-card"><Bookmark /><h3>Đã lưu</h3><strong>2 nội dung</strong><p>Các tình huống tư vấn cần xem lại.</p></article></div><ol className="timeline-list"><li><span><CheckCircle2 /></span><div><strong>Hoàn thành bài “Hiểu nhu cầu khách hàng”</strong><small>Hôm nay · 09:20</small></div></li><li><span><Clock3 /></span><div><strong>Tiếp tục khóa “Tư vấn Mac mùa Back to School”</strong><small>Hôm qua · 15:45</small></div></li><li><span><CalendarDays /></span><div><strong>Khóa học được giao cho chiến dịch Back to School</strong><small>15/07/2026</small></div></li></ol>{pathname === '/progress' && <div className="category-progress"><h2>Tiến độ theo nhóm</h2>{[['Mac', active.progress, 'mac'], ['Soft Skill', 35, 'soft'], ['Ecosystem', 20, 'eco']].map(([label, value, accent]) => <div className={`category-row accent-${accent}`} key={String(label)}><span>{label}</span><ProgressBar value={Number(value)} /><strong>{value}%</strong></div>)}</div>}{pathname === '/history' && <div className="empty-product-state"><Map /><h2>Toàn bộ hoạt động được sắp xếp theo thời gian</h2><p>Bộ lọc khóa học, loại hoạt động và thời gian sẽ được nối dữ liệu ở Sprint backend.</p></div>}</section>
}
