import { Award, BookOpen, RotateCcw } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { QuizSummary } from '../../components/quiz/QuizSummary'
import { useCourse } from '../../hooks/useCourse'
import { useLearningProgress } from '../../hooks/useLearningProgress'
import { quizService } from '../../services/quizService'
import { NotFoundPage } from '../NotFoundPage'

export function ResultsPage() {
  const { courseId } = useParams(); const course = useCourse(courseId); const navigate = useNavigate(); const { progress, updateQuizDraft } = useLearningProgress(); const result = progress.latestQuizResult?.courseId === courseId ? progress.latestQuizResult : null; const questions = courseId ? quizService.getQuestions(courseId) : []
  if (!course) return <NotFoundPage />
  if (!result) return <section className="system-page"><BookOpen /><h1>Chưa có kết quả</h1><p>Hãy hoàn thành bài kiểm tra để xem kết quả.</p><Link className="button button-primary" to={`/quiz/${course.id}`}>Làm quiz</Link></section>
  const retry = () => { updateQuizDraft({ courseId: course.id, answers: {}, currentQuestionIndex: 0, updatedAt: new Date().toISOString() }); navigate(`/quiz/${course.id}`) }
  const wrongLessons = [...new Set(result.answers.filter((answer) => !answer.isCorrect).map((answer) => answer.relatedLessonId))]
  return <section className="result-page container"><div className="result-card"><span className="award-icon"><Award /></span><span className="overline">{result.passed ? 'Đã đạt bài kiểm tra' : 'Chưa đạt bài kiểm tra'}</span><h1>{result.passed ? 'Làm tốt lắm!' : 'Cùng ôn tập thêm nhé'}</h1><p>{new Date(result.completedAt).toLocaleString('vi-VN')}</p><div className="score-ring"><strong>{result.score}</strong><span>/100 điểm</span></div><QuizSummary result={result} /><div className="result-actions"><Link className="button button-primary" to={`/courses/${course.id}`}>Về khóa học</Link><button type="button" className="button button-secondary" onClick={retry}><RotateCcw />Làm lại quiz</button>{!result.passed && wrongLessons[0] && <Link className="button button-secondary" to={`/learn/${course.id}/${wrongLessons[0]}`}><BookOpen />Học nội dung cần cải thiện</Link>}</div></div><section className="answer-review"><h2>Chi tiết đáp án</h2>{result.answers.map((answer, index) => { const question = questions.find((item) => item.id === answer.questionId); if (!question) return null; const selected = answer.selectedOptionIndexes ?? (answer.selectedOptionIndex === null ? [] : [answer.selectedOptionIndex]); const correct = answer.correctOptionIndexes ?? [answer.correctOptionIndex]; return <article key={answer.questionId} className={answer.isCorrect ? 'correct' : 'incorrect'}><h3>Câu {index + 1}: {question.prompt}</h3><p><strong>Đáp án của bạn:</strong> {selected.length ? selected.map((item) => question.options[item]).join(', ') : 'Bỏ trống'}</p><p><strong>Đáp án đúng:</strong> {correct.map((item) => question.options[item]).join(', ')}</p><p>{answer.isCorrect ? '✓ Trả lời đúng' : '✕ Cần ôn lại'} — {answer.explanation}</p><Link to={`/learn/${course.id}/${answer.relatedLessonId}`}>Xem bài học liên quan</Link></article> })}</section></section>
}
