import type { AiApprovalItem, AiCourseDraft, AiDraftBlock, AiDraftLesson, AiDraftModule, AiDraftValidation, AiHealthSection, AiReviewSelection, AiReviewStatus, AiWarningDismissReason } from './types'

let reviewCounter = 0
const reviewId = (kind: string) => { reviewCounter += 1; return `ai-review-${kind}-${Date.now().toString(36)}-${reviewCounter}` }
const isReviewed = (status?: AiReviewStatus) => status === 'reviewed' || status === 'approved'
const move = <T,>(items: T[], index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= items.length) return items; const next = [...items]; [next[index], next[target]] = [next[target]!, next[index]!]; return next }

export function normalizeReviewDraft(draft: AiCourseDraft): AiCourseDraft {
  return { ...draft, review: draft.review ?? { courseTitle: 'unreviewed', courseDescription: 'unreviewed', learningObjectives: 'unreviewed', previewOpened: false }, warnings: draft.warnings.map((item) => ({ ...item, resolution: item.resolution ?? (item.reviewed ? 'resolved' : 'open') })), modules: draft.modules.map((module) => ({ ...module, reviewStatus: module.reviewStatus ?? 'unreviewed', lessons: module.lessons.map((lesson) => ({ ...lesson, reviewStatus: lesson.reviewStatus ?? 'unreviewed', blocks: lesson.blocks.map((block) => ({ ...block, reviewStatus: block.reviewStatus ?? 'unreviewed' })) })) })) }
}

export const renameModule = (draft: AiCourseDraft, moduleId: string, title: string): AiCourseDraft => ({ ...draft, modules: draft.modules.map((module) => module.id === moduleId ? { ...module, title, reviewStatus: 'unreviewed' } : module) })
export const renameLesson = (draft: AiCourseDraft, moduleId: string, lessonId: string, title: string): AiCourseDraft => ({ ...draft, modules: draft.modules.map((module) => module.id === moduleId ? { ...module, lessons: module.lessons.map((lesson) => lesson.id === lessonId ? { ...lesson, title, reviewStatus: 'unreviewed' } : lesson) } : module) })
export const moveModule = (draft: AiCourseDraft, moduleId: string, delta: number): AiCourseDraft => { const index = draft.modules.findIndex((module) => module.id === moduleId); return index < 0 ? draft : { ...draft, modules: move(draft.modules, index, delta) } }
export const moveLesson = (draft: AiCourseDraft, moduleId: string, lessonId: string, delta: number): AiCourseDraft => ({ ...draft, modules: draft.modules.map((module) => { if (module.id !== moduleId) return module; const index = module.lessons.findIndex((lesson) => lesson.id === lessonId); return index < 0 ? module : { ...module, lessons: move(module.lessons, index, delta) } }) })
export const moveBlock = (draft: AiCourseDraft, moduleId: string, lessonId: string, blockId: string, delta: number): AiCourseDraft => ({ ...draft, modules: draft.modules.map((module) => module.id === moduleId ? { ...module, lessons: module.lessons.map((lesson) => { if (lesson.id !== lessonId) return lesson; const index = lesson.blocks.findIndex((block) => block.id === blockId); return index < 0 ? lesson : { ...lesson, blocks: move(lesson.blocks, index, delta) } }) } : module) })

function cloneBlock(block: AiDraftBlock): AiDraftBlock {
  const base = { ...structuredClone(block), id: reviewId('block'), reviewStatus: 'unreviewed' as const }
  if (base.type === 'quick_question') return { ...base, options: base.options.map((item) => ({ ...item, id: reviewId('option') })) }
  if (base.type === 'scenario') return { ...base, options: base.options.map((item) => ({ ...item, id: reviewId('option') })) }
  if (base.type === 'flashcard') return { ...base, cards: base.cards.map((item) => ({ ...item, id: reviewId('card') })) }
  return base
}
function cloneLesson(lesson: AiDraftLesson): AiDraftLesson { return { ...structuredClone(lesson), id: reviewId('lesson'), title: `${lesson.title} (Bản sao)`, reviewStatus: 'unreviewed', blocks: lesson.blocks.map(cloneBlock) } }
function cloneModule(module: AiDraftModule): AiDraftModule { return { ...structuredClone(module), id: reviewId('module'), title: `${module.title} (Bản sao)`, reviewStatus: 'unreviewed', lessons: module.lessons.map(cloneLesson) } }
export const duplicateModule = (draft: AiCourseDraft, moduleId: string): AiCourseDraft => { const index = draft.modules.findIndex((module) => module.id === moduleId); if (index < 0) return draft; return { ...draft, modules: [...draft.modules.slice(0, index + 1), cloneModule(draft.modules[index]!), ...draft.modules.slice(index + 1)] } }
export const duplicateLesson = (draft: AiCourseDraft, moduleId: string, lessonId: string): AiCourseDraft => ({ ...draft, modules: draft.modules.map((module) => { if (module.id !== moduleId) return module; const index = module.lessons.findIndex((lesson) => lesson.id === lessonId); return index < 0 ? module : { ...module, lessons: [...module.lessons.slice(0, index + 1), cloneLesson(module.lessons[index]!), ...module.lessons.slice(index + 1)] } }) })
export const duplicateBlock = (draft: AiCourseDraft, moduleId: string, lessonId: string, blockId: string): AiCourseDraft => ({ ...draft, modules: draft.modules.map((module) => module.id === moduleId ? { ...module, lessons: module.lessons.map((lesson) => { if (lesson.id !== lessonId) return lesson; const index = lesson.blocks.findIndex((block) => block.id === blockId); return index < 0 ? lesson : { ...lesson, blocks: [...lesson.blocks.slice(0, index + 1), cloneBlock(lesson.blocks[index]!), ...lesson.blocks.slice(index + 1)] } }) } : module) })

export const deleteModule = (draft: AiCourseDraft, moduleId: string): AiCourseDraft => ({ ...draft, modules: draft.modules.filter((module) => module.id !== moduleId) })
export const deleteLesson = (draft: AiCourseDraft, moduleId: string, lessonId: string): AiCourseDraft => ({ ...draft, modules: draft.modules.map((module) => module.id === moduleId ? { ...module, lessons: module.lessons.filter((lesson) => lesson.id !== lessonId) } : module) })
export const deleteBlock = (draft: AiCourseDraft, moduleId: string, lessonId: string, blockId: string): AiCourseDraft => ({ ...draft, modules: draft.modules.map((module) => module.id === moduleId ? { ...module, lessons: module.lessons.map((lesson) => lesson.id === lessonId ? { ...lesson, blocks: lesson.blocks.filter((block) => block.id !== blockId) } : lesson) } : module) })

export function mergeModules(draft: AiCourseDraft, moduleId: string, title: string): AiCourseDraft { const index = draft.modules.findIndex((module) => module.id === moduleId); if (index < 0 || index >= draft.modules.length - 1) return draft; const current = draft.modules[index]!; const next = draft.modules[index + 1]!; const merged = { ...current, id: reviewId('module'), title, lessons: [...current.lessons, ...next.lessons], reviewStatus: 'unreviewed' as const }; return { ...draft, modules: [...draft.modules.slice(0, index), merged, ...draft.modules.slice(index + 2)] } }
export function mergeLessons(draft: AiCourseDraft, moduleId: string, lessonId: string, title: string): AiCourseDraft { return { ...draft, modules: draft.modules.map((module) => { if (module.id !== moduleId) return module; const index = module.lessons.findIndex((lesson) => lesson.id === lessonId); if (index < 0 || index >= module.lessons.length - 1) return module; const current = module.lessons[index]!; const next = module.lessons[index + 1]!; const merged = { ...current, id: reviewId('lesson'), title, blocks: [...current.blocks, ...next.blocks], reviewStatus: 'unreviewed' as const }; return { ...module, lessons: [...module.lessons.slice(0, index), merged, ...module.lessons.slice(index + 2)] } }) } }
export function splitLesson(draft: AiCourseDraft, moduleId: string, lessonId: string, splitIndex: number, firstTitle: string, secondTitle: string): AiCourseDraft { return { ...draft, modules: draft.modules.map((module) => { if (module.id !== moduleId) return module; const index = module.lessons.findIndex((lesson) => lesson.id === lessonId); const source = module.lessons[index]; if (!source || source.blocks.length < 2 || splitIndex < 1 || splitIndex >= source.blocks.length) return module; const first = { ...source, id: reviewId('lesson'), title: firstTitle, blocks: source.blocks.slice(0, splitIndex), reviewStatus: 'unreviewed' as const }; const second = { ...source, id: reviewId('lesson'), title: secondTitle, blocks: source.blocks.slice(splitIndex), reviewStatus: 'unreviewed' as const }; return { ...module, lessons: [...module.lessons.slice(0, index), first, second, ...module.lessons.slice(index + 1)] } }) } }
export type LessonDestination = 'start' | 'end' | { beforeId: string } | { afterId: string }
export function moveLessonToModule(draft: AiCourseDraft, sourceModuleId: string, lessonId: string, destinationModuleId: string, destination: LessonDestination): AiCourseDraft { if (sourceModuleId === destinationModuleId) return draft; const source = draft.modules.find((module) => module.id === sourceModuleId); const lesson = source?.lessons.find((item) => item.id === lessonId); if (!lesson || !draft.modules.some((module) => module.id === destinationModuleId)) return draft; return { ...draft, modules: draft.modules.map((module) => { if (module.id === sourceModuleId) return { ...module, lessons: module.lessons.filter((item) => item.id !== lessonId) }; if (module.id !== destinationModuleId) return module; let index = destination === 'start' ? 0 : destination === 'end' ? module.lessons.length : 'beforeId' in destination ? module.lessons.findIndex((item) => item.id === destination.beforeId) : module.lessons.findIndex((item) => item.id === destination.afterId) + 1; if (index < 0) index = module.lessons.length; return { ...module, lessons: [...module.lessons.slice(0, index), lesson, ...module.lessons.slice(index)] } }) } }

export function markReviewStatus(draft: AiCourseDraft, selection: AiReviewSelection, status: AiReviewStatus): AiCourseDraft { if (selection.type === 'course') return { ...draft, review: { ...(draft.review ?? { courseTitle: 'unreviewed', courseDescription: 'unreviewed', learningObjectives: 'unreviewed', previewOpened: false }), courseTitle: status, courseDescription: status, learningObjectives: status } }; return { ...draft, modules: draft.modules.map((module) => { if (module.id !== selection.moduleId) return module; if (selection.type === 'module') return { ...module, reviewStatus: status }; return { ...module, lessons: module.lessons.map((lesson) => { if (lesson.id !== selection.lessonId) return lesson; if (selection.type === 'lesson') return { ...lesson, reviewStatus: status }; return { ...lesson, blocks: lesson.blocks.map((block) => block.id === selection.blockId ? { ...block, reviewStatus: status } : block) } }) } }) } }
export const resolveWarning = (draft: AiCourseDraft, warningId: string): AiCourseDraft => ({ ...draft, warnings: draft.warnings.map((warning) => warning.id === warningId ? { ...warning, reviewed: true, resolution: 'resolved', dismissReason: undefined } : warning) })
export const dismissWarning = (draft: AiCourseDraft, warningId: string, reason: AiWarningDismissReason): AiCourseDraft => ({ ...draft, warnings: draft.warnings.map((warning) => warning.id === warningId ? { ...warning, reviewed: true, resolution: 'dismissed', dismissReason: reason } : warning) })
export const restoreWarning = (draft: AiCourseDraft, warningId: string): AiCourseDraft => ({ ...draft, warnings: draft.warnings.map((warning) => warning.id === warningId ? { ...warning, reviewed: false, resolution: 'open', dismissReason: undefined } : warning) })

export type RegenerateAction = 'course_title' | 'course_description' | 'learning_objectives' | 'module_title' | 'lesson_title' | 'lesson_summary' | 'quiz' | 'flashcard' | 'scenario' | 'simplify' | 'sales_focus' | 'concise'
export interface RegenerateProposal { action: RegenerateAction; selection: AiReviewSelection; before: string; after: string }
export function createRegenerateProposal(draft: AiCourseDraft, selection: AiReviewSelection, action: RegenerateAction): RegenerateProposal | null { const module = selection.type !== 'course' ? draft.modules.find((item) => item.id === selection.moduleId) : undefined; const lesson = selection.type === 'lesson' || selection.type === 'block' ? module?.lessons.find((item) => item.id === selection.lessonId) : undefined; const block = selection.type === 'block' ? lesson?.blocks.find((item) => item.id === selection.blockId) : undefined; if (action === 'course_title') return { action, selection, before: draft.title, after: `${draft.category} · Thực hành tại F.Studio` }; if (action === 'course_description') return { action, selection, before: draft.shortDescription, after: 'Khóa học ngắn gọn giúp nhân viên hiểu kiến thức trọng tâm và áp dụng ngay trong tư vấn tại cửa hàng.' }; if (action === 'learning_objectives') return { action, selection, before: draft.learningObjectives.join('\n'), after: ['Nhận diện đúng nhu cầu khách hàng', 'Trình bày giá trị bằng ngôn ngữ dễ hiểu', 'Áp dụng nhất quán tại cửa hàng'].join('\n') }; if (action === 'module_title' && module) return { action, selection, before: module.title, after: `${module.title} · Thực hành` }; if (action === 'lesson_title' && lesson) return { action, selection, before: lesson.title, after: `${lesson.title} trong tư vấn` }; if (action === 'lesson_summary' && lesson) return { action, selection, before: blockLabel(lesson.blocks[lesson.blocks.length - 1]), after: 'Tóm tắt ngắn: xác nhận nhu cầu, giải thích giá trị và chốt bước tiếp theo.' }; if (action === 'quiz') return { action, selection, before: `${draft.quiz.questions.length} câu hỏi`, after: '3 câu hỏi được chuẩn hóa theo mục tiêu học tập' }; if (block && (action === 'flashcard' || action === 'scenario' || action === 'simplify' || action === 'sales_focus' || action === 'concise')) { const before = blockLabel(block); const prefix = action === 'sales_focus' ? 'Ứng dụng bán hàng: ' : action === 'simplify' ? 'Dễ hiểu: ' : action === 'concise' ? 'Tóm tắt: ' : action === 'flashcard' ? 'Flashcard đã chuẩn hóa: ' : 'Scenario đã chuẩn hóa: '; return { action, selection, before, after: `${prefix}${before}` } } return null }
function blockLabel(block?: AiDraftBlock) { if (!block) return ''; switch (block.type) { case 'heading': case 'paragraph': return block.text; case 'key_point': case 'warning': return block.text; case 'bullet_list': case 'checklist': case 'flashcard': return block.title; case 'quick_question': return block.question; case 'scenario': return block.context; case 'sorting': return block.prompt } }
export function applyRegenerateProposal(draft: AiCourseDraft, proposal: RegenerateProposal, editedAfter = proposal.after): AiCourseDraft {
  const { action, selection } = proposal
  if (action === 'course_title') return { ...draft, title: editedAfter }
  if (action === 'course_description') return { ...draft, shortDescription: editedAfter }
  if (action === 'learning_objectives') return { ...draft, learningObjectives: editedAfter.split('\n').map((item) => item.trim()).filter(Boolean) }
  if (action === 'quiz') return { ...draft, quiz: { ...draft.quiz, questions: draft.quiz.questions.slice(0, 3).map((question, index) => ({ ...question, prompt: `Câu ${index + 1}: ${question.prompt.replace(/^Câu \d+: /, '')}` })) } }
  if (selection.type === 'module' && action === 'module_title') return renameModule(draft, selection.moduleId, editedAfter)
  if ((selection.type === 'lesson' || selection.type === 'block') && action === 'lesson_title') return renameLesson(draft, selection.moduleId, selection.lessonId, editedAfter)
  if (selection.type === 'lesson' && action === 'lesson_summary') return { ...draft, modules: draft.modules.map((module) => module.id === selection.moduleId ? { ...module, lessons: module.lessons.map((lesson) => lesson.id === selection.lessonId ? { ...lesson, blocks: lesson.blocks.map((block, index) => index === lesson.blocks.length - 1 ? replaceBlockText(block, editedAfter) : block) } : lesson) } : module) }
  if (selection.type === 'block') return { ...draft, modules: draft.modules.map((module) => module.id === selection.moduleId ? { ...module, lessons: module.lessons.map((lesson) => lesson.id === selection.lessonId ? { ...lesson, blocks: lesson.blocks.map((block) => block.id === selection.blockId ? replaceBlockText(block, editedAfter) : block) } : lesson) } : module) }
  return draft
}
function replaceBlockText(block: AiDraftBlock, text: string): AiDraftBlock { switch (block.type) { case 'heading': case 'paragraph': return { ...block, text }; case 'key_point': case 'warning': return { ...block, text }; case 'bullet_list': case 'checklist': case 'flashcard': return { ...block, title: text }; case 'quick_question': return { ...block, question: text }; case 'scenario': return { ...block, context: text }; case 'sorting': return { ...block, prompt: text } } }

export function calculateReviewProgress(draft: AiCourseDraft) { const modules = draft.modules; const lessons = modules.flatMap((module) => module.lessons); const blocks = lessons.flatMap((lesson) => lesson.blocks); const total = modules.length + lessons.length + blocks.length; const reviewed = modules.filter((item) => isReviewed(item.reviewStatus)).length + lessons.filter((item) => isReviewed(item.reviewStatus)).length + blocks.filter((item) => isReviewed(item.reviewStatus)).length; return { modulesReviewed: modules.filter((item) => isReviewed(item.reviewStatus)).length, modulesTotal: modules.length, lessonsReviewed: lessons.filter((item) => isReviewed(item.reviewStatus)).length, lessonsTotal: lessons.length, blocksReviewed: blocks.filter((item) => isReviewed(item.reviewStatus)).length, blocksTotal: blocks.length, unresolvedWarnings: draft.warnings.filter((item) => (item.resolution ?? 'open') === 'open').length, percentage: total ? Math.round(reviewed / total * 100) : 0 } }
export function calculateDraftHealth(draft: AiCourseDraft, validation: AiDraftValidation): AiHealthSection[] { const lessons = draft.modules.flatMap((module) => module.lessons); const blocks = lessons.flatMap((lesson) => lesson.blocks); const progress = calculateReviewProgress(draft); const sections: AiHealthSection[] = [
  { id: 'structure', label: 'Structure', passed: 0, total: 3, rules: [{ id: 'modules', label: 'Có module', passed: draft.modules.length > 0 }, { id: 'module-lessons', label: 'Mỗi module có lesson', passed: draft.modules.length > 0 && draft.modules.every((module) => module.lessons.length > 0) }, { id: 'lesson-blocks', label: 'Mỗi lesson có block', passed: lessons.length > 0 && lessons.every((lesson) => lesson.blocks.length > 0) }] },
  { id: 'content', label: 'Content completeness', passed: 0, total: 2, rules: [{ id: 'objectives', label: 'Có learning objectives', passed: draft.learningObjectives.length > 0 }, { id: 'nonempty', label: 'Không có lesson rỗng', passed: lessons.length > 0 && lessons.every((lesson) => lesson.blocks.length > 0) }] },
  { id: 'assessment', label: 'Assessment readiness', passed: 0, total: 3, rules: [{ id: 'quiz', label: 'Có quiz', passed: draft.quiz.questions.length > 0 }, { id: 'score', label: 'Pass score hợp lệ', passed: draft.quiz.passScore >= 0 && draft.quiz.passScore <= 100 }, { id: 'answers', label: 'Câu hỏi có đáp án', passed: draft.quiz.questions.every((question) => question.options.length >= 2 && question.correctOptionIndexes.length > 0) }] },
  { id: 'sales', label: 'Sales relevance', passed: 0, total: 3, rules: [{ id: 'scenario', label: 'Có scenario', passed: blocks.some((block) => block.type === 'scenario') }, { id: 'objection', label: 'Có objection handling', passed: blocks.some((block) => block.type === 'scenario' && /giá|ngân sách|phan doi|objection/i.test(JSON.stringify(block))) }, { id: 'store', label: 'Có Apply at Store', passed: blocks.some((block) => block.type === 'checklist') }] },
  { id: 'review', label: 'Review progress', passed: progress.percentage, total: 100, rules: [{ id: 'items', label: `${progress.percentage}% item đã review`, passed: progress.percentage === 100 }] },
  { id: 'validation', label: 'Validation status', passed: validation.errors.length ? 0 : 1, total: 1, rules: [{ id: 'valid', label: 'Không có validation error', passed: validation.errors.length === 0 }] },
  ]; return sections.map((section) => section.id === 'review' ? section : { ...section, passed: section.rules.filter((rule) => rule.passed).length, total: section.rules.length }) }
export function getApprovalChecklist(draft: AiCourseDraft, validation: AiDraftValidation): AiApprovalItem[] { const review = draft.review ?? { courseTitle: 'unreviewed', courseDescription: 'unreviewed', learningObjectives: 'unreviewed', previewOpened: false }; const lessons = draft.modules.flatMap((module) => module.lessons); return [
  { id: 'title', label: 'Course title đã review', complete: isReviewed(review.courseTitle) }, { id: 'description', label: 'Course description đã review', complete: isReviewed(review.courseDescription) }, { id: 'objectives', label: 'Learning objectives đã review', complete: isReviewed(review.learningObjectives) },
  { id: 'modules', label: 'Tất cả Module đã review', complete: draft.modules.length > 0 && draft.modules.every((module) => isReviewed(module.reviewStatus)) }, { id: 'lessons', label: 'Tất cả Lesson đã review', complete: lessons.length > 0 && lessons.every((lesson) => isReviewed(lesson.reviewStatus)) }, { id: 'validation', label: 'Không còn validation error', complete: validation.errors.length === 0 },
  { id: 'warnings', label: 'Warning quan trọng đã xử lý', complete: draft.warnings.every((warning) => (warning.resolution ?? 'open') !== 'open') }, { id: 'quiz', label: 'Quiz hợp lệ', complete: draft.quiz.questions.length > 0 && draft.quiz.questions.every((question) => question.options.length >= 2 && question.correctOptionIndexes.length > 0) },
  { id: 'lessons-content', label: 'Không có Lesson rỗng', complete: lessons.length > 0 && lessons.every((lesson) => lesson.blocks.length > 0) }, { id: 'blocks-content', label: 'Không có Block rỗng', complete: !validation.errors.some((issue) => issue.id.startsWith('block-content')) }, { id: 'preview', label: 'Preview đã được mở', complete: review.previewOpened },
  ] }
