import { GitMerge, Scissors, Trash2, ArrowDown, ArrowUp } from 'lucide-react'
import type { AiCourseDraft, AiDraftBlock } from './types'

interface AiReviewTreeProps { draft: AiCourseDraft; onChange(draft: AiCourseDraft): void }
const blockLabel = (block: AiDraftBlock) => { switch (block.type) { case 'heading': case 'paragraph': return block.text; case 'key_point': case 'warning': case 'bullet_list': case 'checklist': case 'flashcard': return block.title; case 'quick_question': return block.question; case 'scenario': return block.context; case 'sorting': return block.prompt } }

export function AiReviewTree({ draft, onChange }: AiReviewTreeProps) {
  const replaceModules = (modules: AiCourseDraft['modules']) => onChange({ ...draft, modules })
  const updateModule = (moduleIndex: number, title: string) => replaceModules(draft.modules.map((module, index) => index === moduleIndex ? { ...module, title } : module))
  const deleteModule = (moduleIndex: number) => replaceModules(draft.modules.filter((_, index) => index !== moduleIndex))
  const moveModule = (moduleIndex: number, delta: number) => { const target = moduleIndex + delta; if (target < 0 || target >= draft.modules.length) return; const modules = [...draft.modules]; [modules[moduleIndex], modules[target]] = [modules[target]!, modules[moduleIndex]!]; replaceModules(modules) }
  const updateLessons = (moduleIndex: number, lessons: AiCourseDraft['modules'][number]['lessons']) => replaceModules(draft.modules.map((module, index) => index === moduleIndex ? { ...module, lessons } : module))
  const updateLesson = (moduleIndex: number, lessonIndex: number, title: string) => updateLessons(moduleIndex, draft.modules[moduleIndex]!.lessons.map((lesson, index) => index === lessonIndex ? { ...lesson, title } : lesson))
  const deleteLesson = (moduleIndex: number, lessonIndex: number) => updateLessons(moduleIndex, draft.modules[moduleIndex]!.lessons.filter((_, index) => index !== lessonIndex))
  const moveLesson = (moduleIndex: number, lessonIndex: number, delta: number) => { const lessons = [...draft.modules[moduleIndex]!.lessons]; const target = lessonIndex + delta; if (target < 0 || target >= lessons.length) return; [lessons[lessonIndex], lessons[target]] = [lessons[target]!, lessons[lessonIndex]!]; updateLessons(moduleIndex, lessons) }
  const deleteBlock = (moduleIndex: number, lessonIndex: number, blockIndex: number) => updateLessons(moduleIndex, draft.modules[moduleIndex]!.lessons.map((lesson, index) => index === lessonIndex ? { ...lesson, blocks: lesson.blocks.filter((_, childIndex) => childIndex !== blockIndex) } : lesson))
  const mergeLesson = (moduleIndex: number, lessonIndex: number) => { if (lessonIndex === 0) return; const lessons = draft.modules[moduleIndex]!.lessons; const previous = lessons[lessonIndex - 1]!; const current = lessons[lessonIndex]!; updateLessons(moduleIndex, lessons.map((lesson, index) => index === lessonIndex - 1 ? { ...previous, title: `${previous.title} & ${current.title}`, blocks: [...previous.blocks, ...current.blocks] } : lesson).filter((_, index) => index !== lessonIndex)) }
  const splitLesson = (moduleIndex: number, lessonIndex: number) => { const lessons = draft.modules[moduleIndex]!.lessons; const source = lessons[lessonIndex]!; const pivot = Math.max(1, Math.ceil(source.blocks.length / 2)); const first = { ...source, title: `${source.title} · Phần 1`, blocks: source.blocks.slice(0, pivot) }; const second = { ...source, id: `${source.id}-split-${lessons.length}`, title: `${source.title} · Phần 2`, blocks: source.blocks.slice(pivot) }; updateLessons(moduleIndex, [...lessons.slice(0, lessonIndex), first, second, ...lessons.slice(lessonIndex + 1)]) }

  return <div className="ai-review-tree">{draft.modules.map((module, moduleIndex) => <article className="ai-module-card" key={module.id}><header><span>Module {moduleIndex + 1} · {module.confidence}</span><input aria-label={`Tên module ${moduleIndex + 1}`} value={module.title} onChange={(event) => updateModule(moduleIndex, event.target.value)} /><span className="ai-review-icon-actions"><button type="button" className="icon-button" aria-label={`Di chuyển module ${module.title} lên`} disabled={moduleIndex === 0} onClick={() => moveModule(moduleIndex, -1)}><ArrowUp /></button><button type="button" className="icon-button" aria-label={`Di chuyển module ${module.title} xuống`} disabled={moduleIndex === draft.modules.length - 1} onClick={() => moveModule(moduleIndex, 1)}><ArrowDown /></button><button type="button" className="icon-button danger" aria-label={`Xóa module ${module.title}`} onClick={() => deleteModule(moduleIndex)}><Trash2 /></button></span></header><div className="ai-lessons">{module.lessons.map((lesson, lessonIndex) => <section className="ai-lesson-card" key={lesson.id}><div className="ai-lesson-heading"><span>Lesson {lessonIndex + 1} · {lesson.confidence}</span><input aria-label={`Tên lesson ${lessonIndex + 1} của module ${moduleIndex + 1}`} value={lesson.title} onChange={(event) => updateLesson(moduleIndex, lessonIndex, event.target.value)} /><div><button type="button" className="icon-button" aria-label={`Di chuyển ${lesson.title} lên`} disabled={lessonIndex === 0} onClick={() => moveLesson(moduleIndex, lessonIndex, -1)}><ArrowUp /></button><button type="button" className="icon-button" aria-label={`Di chuyển ${lesson.title} xuống`} disabled={lessonIndex === module.lessons.length - 1} onClick={() => moveLesson(moduleIndex, lessonIndex, 1)}><ArrowDown /></button><button type="button" className="icon-button" aria-label={`Merge ${lesson.title}`} disabled={lessonIndex === 0} onClick={() => mergeLesson(moduleIndex, lessonIndex)}><GitMerge /></button><button type="button" className="icon-button" aria-label={`Split ${lesson.title}`} disabled={lesson.blocks.length < 2} onClick={() => splitLesson(moduleIndex, lessonIndex)}><Scissors /></button><button type="button" className="icon-button danger" aria-label={`Xóa lesson ${lesson.title}`} onClick={() => deleteLesson(moduleIndex, lessonIndex)}><Trash2 /></button></div></div><div className="ai-block-list">{lesson.blocks.map((item, blockIndex) => <span key={item.id}><small>{item.type} · {item.confidence}</small><span>{blockLabel(item)}</span><button type="button" className="icon-button danger" aria-label={`Xóa block ${blockLabel(item)}`} onClick={() => deleteBlock(moduleIndex, lessonIndex, blockIndex)}><Trash2 /></button></span>)}</div></section>)}</div></article>)}</div>
}
