import { Download, FileWarning } from 'lucide-react'
import { useState } from 'react'
import type { DocumentElement, StructuredDocument } from '../../document/types'
import { documentService } from '../../document/services/documentService'

export function DocumentPreview({ document, rawText }: { document: StructuredDocument; rawText: string }) {
  const [tab, setTab] = useState<'raw' | 'normalized' | 'detected'>('normalized')
  const exportJson = () => { const blob = new Blob([documentService.exportNormalized(document)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = window.document.createElement('a'); anchor.href = url; anchor.download = `${document.source.fileName.replace(/\.[^.]+$/, '')}-normalized.json`; anchor.click(); URL.revokeObjectURL(url) }
  return <section className="document-preview" aria-label="Document Intelligence Preview">
    <header><div><span className="ui-eyebrow">Document Intelligence</span><h3>{document.metadata.title}</h3><p>{document.source.format.toUpperCase()} · {document.metadata.wordCount} từ · Quality {document.quality.score}%</p></div><button type="button" className="button button-secondary" onClick={exportJson}><Download /> Export Normalized JSON</button></header>
    {document.status === 'parser_unavailable' && <div className="document-parser-warning" role="status"><FileWarning /><span>Định dạng đã nhận diện nhưng parser chưa khả dụng</span></div>}
    <nav aria-label="Document preview modes"><button type="button" className={tab === 'raw' ? 'active' : ''} onClick={() => setTab('raw')}>Raw</button><button type="button" className={tab === 'normalized' ? 'active' : ''} onClick={() => setTab('normalized')}>Normalized</button><button type="button" className={tab === 'detected' ? 'active' : ''} onClick={() => setTab('detected')}>Detected Structure</button></nav>
    {tab === 'raw' && <pre>{rawText || 'Binary raw content không được render hoặc gửi tới AI.'}</pre>}
    {tab === 'normalized' && <div className="document-sections">{document.pages.flatMap((page) => page.sections).map((section) => <article key={section.id}><h4>{section.title}</h4>{section.elements.map((element) => <DocumentElementPreview key={element.id} element={element} />)}</article>)}</div>}
    {tab === 'detected' && <div className="document-detected"><section><h4>Retail signals</h4><div>{document.detectedSignals.length ? document.detectedSignals.map((signal) => <span className="badge" key={signal}>{signal}</span>) : <p>Chưa nhận diện tín hiệu bán lẻ.</p>}</div></section><section><h4>Quality rules</h4><ul>{document.quality.rules.map((rule) => <li key={rule.id} className={rule.passed ? 'passed' : ''}>{rule.passed ? '✓' : '○'} {rule.label}</li>)}</ul></section><section><h4>Metadata</h4><dl><div><dt>Parser</dt><dd>{document.metadata.parserId}</dd></div><div><dt>Pages</dt><dd>{document.metadata.pageCount ?? '—'}</dd></div><div><dt>Slides</dt><dd>{document.metadata.slideCount ?? '—'}</dd></div></dl></section></div>}
  </section>
}

function DocumentElementPreview({ element }: { element: DocumentElement }) { switch (element.type) { case 'heading': return <h5>{element.text}</h5>; case 'subtitle': return <h6>{element.text}</h6>; case 'paragraph': return <p>{element.text}</p>; case 'speaker_note': return <p><strong>Speaker note:</strong> {element.text}</p>; case 'shape': return <p><strong>{element.shapeKind}:</strong> {element.text}</p>; case 'chart': return <p><strong>{element.title}</strong> {element.description}</p>; case 'list': return element.ordered ? <ol>{element.items.map((item) => <li key={item}>{item}</li>)}</ol> : <ul>{element.items.map((item) => <li key={item}>{item}</li>)}</ul>; case 'quote': return <blockquote>{element.text}</blockquote>; case 'code': return <pre>{element.code}</pre>; case 'image': return <p>Image: {element.alt || element.src}</p>; case 'table': return <div className="document-table"><table><thead><tr>{element.headers.map((cell) => <th key={cell}>{cell}</th>)}</tr></thead><tbody>{element.rows.map((row, index) => <tr key={`${element.id}-${index}`}>{row.map((cell, cellIndex) => <td key={`${element.id}-${index}-${cellIndex}`}>{cell}</td>)}</tr>)}</tbody></table></div>; case 'placeholder': return <p>{element.message}</p>; case 'blank_line': return <span className="document-blank" aria-hidden="true" /> } }
