import { AlertTriangle, ArrowDown, ArrowUp, Check, FileText, Plus, ShieldCheck, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { instructionalGraphService } from '../../ai/instructional/instructionalPersistence'
import { addObjective, deleteObjective, dismissInstructionalWarning, editObjective, markObjectiveReviewed, markUnitReviewed, reorderUnit, resolveInstructionalWarning, setObjectivePriority, setUnitFormat } from '../../ai/instructional/instructionalTransform'
import type { InstructionalGraph, ObjectivePriority, RecommendedFormat } from '../../ai/instructional/instructionalGraph'
import { validateInstructionalGraph } from '../../ai/instructional/instructionalValidation'

type Tab = 'objectives' | 'structure' | 'assessment' | 'warnings'
interface Props { initialGraph: InstructionalGraph; onApprove: (graph: InstructionalGraph) => void; onDiscard: (graph: InstructionalGraph) => void; onArchive: (graph: InstructionalGraph) => void }
const formats: RecommendedFormat[] = ['explanation', 'comparison', 'checklist', 'walkthrough', 'scenario', 'flashcard', 'quick_question', 'quiz', 'sorting', 'matching', 'image_explanation', 'video_explanation', 'store_practice']

export function InstructionalReviewWorkspace({ initialGraph, onApprove, onDiscard, onArchive }: Props) {
  const [graph, setGraph] = useState(initialGraph)
  const [tab, setTab] = useState<Tab>('objectives')
  const validation = useMemo(() => validateInstructionalGraph(graph), [graph])
  const openImportant = graph.warnings.filter((item) => item.important && item.resolution === 'open')
  const ready = graph.goalReviewed && graph.sourceCoverage.coverageViewed && graph.learningObjectives.length > 0 && graph.learningObjectives.every((item) => item.reviewStatus === 'reviewed' || item.reviewStatus === 'approved') && graph.instructionalUnits.every((item) => item.reviewStatus === 'reviewed' || item.reviewStatus === 'approved') && validation.errors.length === 0 && openImportant.length === 0
  useEffect(() => { const timer = window.setTimeout(() => instructionalGraphService.save(graph), 250); return () => window.clearTimeout(timer) }, [graph])
  const update = (next: InstructionalGraph) => setGraph(next)
  const sourceCount = new Set(graph.instructionalUnits.flatMap((unit) => unit.sourceReferences.map((ref) => ref.sectionId))).size
  return <section className="instructional-review">
    <header className="instructional-toolbar"><div><span className="ui-eyebrow">Instructional Graph · {graph.analysisType === 'rule_based' ? 'Rule-based' : `${graph.provider} · ${graph.model}`}</span><h2>{graph.titleSuggestion}</h2><small>{graph.instructionalUnits.length} unit · {graph.learningObjectives.length} objective · source grounded</small></div><div><button type="button" className="button button-secondary" onClick={() => onArchive(graph)}>Lưu trữ</button><button type="button" className="button button-danger" onClick={() => onDiscard(graph)}>Loại bỏ</button></div></header>
    {graph.analysisType === 'rule_based' && <div className="builder-notice" role="status"><AlertTriangle /> Kết quả rule-based, không phải AI provider thật. Trainer phải xác minh từng mục.</div>}
    <nav className="instructional-tabs" aria-label="Instructional review"><button type="button" className={tab === 'objectives' ? 'active' : ''} onClick={() => setTab('objectives')}>Mục tiêu</button><button type="button" className={tab === 'structure' ? 'active' : ''} onClick={() => setTab('structure')}>Cấu trúc</button><button type="button" className={tab === 'assessment' ? 'active' : ''} onClick={() => setTab('assessment')}>Đánh giá</button><button type="button" className={tab === 'warnings' ? 'active' : ''} onClick={() => setTab('warnings')}>Cảnh báo ({openImportant.length})</button></nav>
    <div className="instructional-grid">
      <aside className="instructional-source"><h3><FileText /> Source traceability</h3><p>{sourceCount}/{graph.sourceCoverage.totalSections} section được sử dụng</p><progress max="100" value={graph.sourceCoverage.percentage}>{graph.sourceCoverage.percentage}%</progress><strong>{graph.sourceCoverage.percentage}% coverage</strong>{graph.contentMap.map((item) => <article key={item.id}><span>{item.type}</span><small>{item.reason}</small><em>{item.sourceReferences[0]?.excerpt}</em></article>)}<button type="button" className="button button-secondary" onClick={() => update({ ...graph, sourceCoverage: { ...graph.sourceCoverage, coverageViewed: true } })}>{graph.sourceCoverage.coverageViewed ? <Check /> : <ShieldCheck />} Đã kiểm tra coverage</button></aside>
      <main className="instructional-editor">
        {tab === 'objectives' && <><label className="cms-field"><span>Overall learning goal</span><textarea value={graph.overallLearningGoal} onChange={(event) => update({ ...graph, overallLearningGoal: event.target.value, goalReviewed: false })} /></label><button type="button" className="button button-secondary" onClick={() => update({ ...graph, goalReviewed: true })}><Check /> Xác nhận learning goal</button><div className="instructional-list">{graph.learningObjectives.map((objective) => <article key={objective.id}><textarea aria-label="Learning objective" value={objective.statement} onChange={(event) => update(editObjective(graph, objective.id, event.target.value))} /><div><select aria-label="Priority" value={objective.priority} onChange={(event) => update(setObjectivePriority(graph, objective.id, event.target.value as ObjectivePriority))}><option value="must">Must</option><option value="should">Should</option><option value="could">Could</option></select><span>{objective.bloomLevel} · {objective.confidence}</span><button type="button" className="icon-button" aria-label="Xóa objective" onClick={() => update(deleteObjective(graph, objective.id))}><Trash2 /></button><button type="button" className="button button-secondary" onClick={() => update(markObjectiveReviewed(graph, objective.id))}><Check /> Đã review</button></div><small>Nguồn: {objective.sourceReferences[0]?.excerpt}</small></article>)}</div><button type="button" className="button button-secondary" onClick={() => update(addObjective(graph))}><Plus /> Thêm objective</button></>}
        {tab === 'structure' && <div className="instructional-list">{[...graph.instructionalUnits].sort((a,b) => a.sequenceIndex-b.sequenceIndex).map((unit, index) => <article key={unit.id}><header><span>Unit {unit.sequenceIndex}</span><strong>{unit.proposedTitle}</strong><div><button type="button" className="icon-button" disabled={index === 0} aria-label="Di chuyển lên" onClick={() => update(reorderUnit(graph, unit.id, -1))}><ArrowUp /></button><button type="button" className="icon-button" disabled={index === graph.instructionalUnits.length - 1} aria-label="Di chuyển xuống" onClick={() => update(reorderUnit(graph, unit.id, 1))}><ArrowDown /></button></div></header><p>{unit.purpose}</p><dl><div><dt>Format</dt><dd><select value={unit.recommendedFormat} onChange={(event) => update(setUnitFormat(graph, unit.id, event.target.value as RecommendedFormat))}>{formats.map((format) => <option key={format}>{format}</option>)}</select></dd></div><div><dt>Load</dt><dd>{unit.cognitiveLoad} · {unit.estimatedDuration} phút</dd></div><div><dt>Why here?</dt><dd>{unit.sequenceRationale}</dd></div></dl><small>Nguồn: {unit.sourceReferences[0]?.excerpt}</small><button type="button" className="button button-secondary" onClick={() => update(markUnitReviewed(graph, unit.id))}><Check /> Đã review unit</button></article>)}</div>}
        {tab === 'assessment' && <section className="instructional-panel"><h3>Assessment blueprint</h3><p>Coverage objective: <strong>{graph.assessmentPlan.objectiveCoverage}%</strong></p><p>Khuyến nghị: <strong>{graph.assessmentPlan.recommendedQuestionCount} câu</strong></p><div className="tag-row">{graph.assessmentPlan.recommendedQuestionTypes.map((type) => <span key={type}>{type}</span>)}</div><h4>Must-test topics</h4><ul>{graph.assessmentPlan.mustTestTopics.map((topic) => <li key={topic}>{topic}</li>)}</ul><p className="helper-text">Đây là blueprint, chưa sinh quiz production.</p></section>}
        {tab === 'warnings' && <div className="instructional-list">{graph.warnings.map((warning) => <article key={warning.id} className={warning.important ? 'important' : ''}><strong>{warning.message}</strong><small>{warning.code} · {warning.resolution}</small>{warning.resolution === 'open' && <div><button type="button" className="button button-secondary" onClick={() => update(resolveInstructionalWarning(graph, warning.id))}>Đã xử lý</button><button type="button" className="button button-secondary" onClick={() => { const reason = window.prompt('Lý do bỏ qua cảnh báo'); if (reason?.trim()) update(dismissInstructionalWarning(graph, warning.id, reason.trim())) }}>Bỏ qua có lý do</button></div>}</article>)}{graph.assumptions.map((item) => <article key={item.id}><strong>Giả định cần xác minh</strong><p>{item.statement}</p><small>{item.reason}</small></article>)}</div>}
      </main>
      <aside className="instructional-summary"><h3>Readiness</h3><dl><div><dt>Validation errors</dt><dd>{validation.errors.length}</dd></div><div><dt>Warnings</dt><dd>{validation.warnings.length}</dd></div><div><dt>Sales checks</dt><dd>{graph.salesRelevance.metrics.filter((item) => item.passed).length}/{graph.salesRelevance.metrics.length}</dd></div></dl>{graph.salesRelevance.metrics.map((metric) => <p key={metric.id} className={metric.passed ? 'passed' : 'missing'}>{metric.passed ? '✓' : '○'} {metric.label}<small>{metric.reason}</small></p>)}<h4>Approval checklist</h4><ul><li className={graph.goalReviewed ? 'done' : ''}>Learning goal đã review</li><li className={graph.learningObjectives.every((item) => item.reviewStatus === 'reviewed') ? 'done' : ''}>Objectives đã review</li><li className={graph.instructionalUnits.every((item) => item.reviewStatus === 'reviewed') ? 'done' : ''}>Units đã review</li><li className={graph.sourceCoverage.coverageViewed ? 'done' : ''}>Coverage đã xem</li><li className={!openImportant.length ? 'done' : ''}>Important warnings đã xử lý</li></ul><button type="button" className="button button-primary" disabled={!ready} onClick={() => onApprove({ ...graph, reviewStatus: 'approved', status: 'approved', updatedAt: new Date().toISOString() })}><ShieldCheck /> Approve Instructional Graph</button><small>Không tạo Course hoặc publish ở sprint này.</small></aside>
    </div>
  </section>
}
