import type { InstructionalAnalysisRequest, InstructionalAnalysisResponse } from '../../../../../src/ai/instructional/instructionalGraph'
import { mapProviderStatus, ServerAiError } from '../errorMapper'
import type { AiProviderConfig } from '../provider'
import { outputText } from '../responseParser'
import { buildInstructionalPrompt, instructionalSystem } from './promptBuilder'
import { parseInstructionalGraph } from './responseParser'
import { instructionalGraphSchema } from './schema'

export async function analyzeWithProvider(request: InstructionalAnalysisRequest, config: AiProviderConfig, fetcher: typeof fetch = fetch): Promise<InstructionalAnalysisResponse> { const started = Date.now(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), config.timeoutMs); try { const response = await fetcher('https://api.openai.com/v1/responses', { method: 'POST', headers: { authorization: `Bearer ${config.apiKey}`, 'content-type': 'application/json', 'x-client-request-id': request.requestId }, body: JSON.stringify({ model: config.model, store: false, input: [{ role: 'system', content: instructionalSystem }, { role: 'user', content: buildInstructionalPrompt(request) }], text: { format: { type: 'json_schema', name: 'instructional_graph', strict: false, schema: instructionalGraphSchema } } }), signal: controller.signal }); if (!response.ok) throw mapProviderStatus(response.status); const parsed = outputText(await response.json() as unknown); const graph = parseInstructionalGraph(parsed.text); const generatedAt = new Date().toISOString(); return { requestId: request.requestId, graph: { ...graph, provider: 'openai', model: parsed.model ?? config.model, generatedAt, analysisType: 'ai' }, provider: 'openai', model: parsed.model ?? config.model, generatedAt, latencyMs: Date.now() - started, analysisType: 'ai', warnings: [] } } catch (error) { if (controller.signal.aborted) throw new ServerAiError('AI_TIMEOUT', 504, 'Instructional analysis timed out.', true); throw error } finally { clearTimeout(timer) } }
