import type { DocumentHandoff, RetailSignal } from '../../document/types'
import { calculateSalesRelevance } from './instructionalScoring'
import { instructionalId } from './instructionalFixtures'
import { retailSignalToClassification, type AssessmentCandidate, type ClassificationType, type InstructionalAnalysisRequest, type InstructionalGraph, type InstructionalUnit, type LearningObjective, type RecommendedFormat, type SourceReference } from './instructionalGraph'

export function createRuleBasedInstructionalGraph(request: InstructionalAnalysisRequest): InstructionalGraph {
  const timestamp = new Date().toISOString(); const refs = request.document.sections.map((section) => reference(request.document, section)); const classifications = request.document.sections.map((section, index) => { const signals = [...new Set(section.elements.flatMap((item) => item.retailSignals))]; const type = classify(signals); return { id: instructionalId('classification'), type, confidence: signals.length ? 'medium' as const : 'low' as const, reason: signals.length ? `Rule-based: nhận diện ${signals.join(', ')} trong section.` : 'Không đủ retail signal; giữ làm kiến thức tham khảo.', sourceReferences: [refs[index]!] } })
  const learningObjectives: LearningObjective[] = request.document.sections.slice(0, 5).map((section, index) => objective(section.title, classifications[index]!.type, refs[index]!))
  const units: InstructionalUnit[] = request.document.sections.map((section, index) => { const classification = classifications[index]!; const ref = refs[index]!; const format = formatFor(classification.type); const text = section.elements.map((item) => item.content).join(' '); const concepts = Math.max(1, Math.min(8, section.elements.length)); const minutes = Math.max(4, Math.min(18, Math.ceil(text.split(/\s+/).length / 90) + 3)); return { id: instructionalId('unit'), proposedTitle: section.title, purpose: purposeFor(classification.type), linkedObjectives: [learningObjectives[Math.min(index, learningObjectives.length - 1)]?.id].filter(Boolean) as string[], sourceReferences: [ref], contentClassification: [classification.type], recommendedFormat: format, estimatedDuration: minutes, estimatedReadingLoad: text.length > 1_200 ? 'heavy' : text.length > 500 ? 'moderate' : 'light', conceptCount: concepts, cognitiveLoad: minutes > 15 || concepts > 5 ? 'high' : minutes > 9 || concepts > 3 ? 'medium' : 'low', difficulty: index > 3 ? 'intermediate' : 'basic', prerequisites: index ? [`unit:${index}`] : [], keyMessages: [{ text: excerpt(text || section.title), sourceReferences: [ref] }], customerBenefits: classification.type === 'Customer Benefit' || classification.type === 'Key Selling Point' ? [excerpt(text)] : [], commonMistakes: classification.type === 'Common Mistake' || classification.type === 'Warning' ? [excerpt(text)] : [], salesApplications: ['Áp dụng nội dung trong một cuộc tư vấn tại cửa hàng.'], suggestedInteractions: [{ format, rationale: interactionRationale(classification.type), sourceReferences: [ref] }], warnings: minutes > 15 ? ['Unit dài hơn khuyến nghị cho microlearning.'] : [], confidence: classification.confidence, confidenceReason: classification.confidence === 'low' ? 'Section thiếu retail signal rõ ràng.' : undefined, reviewStatus: 'unreviewed', sequenceIndex: index + 1, sequenceRationale: sequenceRationale(classification.type, index), dependencyIds: [] } })
  units.forEach((unit, index) => { if (index > 0) unit.dependencyIds = [units[index - 1]!.id] })
  const candidates: AssessmentCandidate[] = learningObjectives.map((item, index) => ({ id: instructionalId('assessment'), objectiveId: item.id, sourceReferences: item.sourceReferences, rationale: 'Kiểm tra hành vi được mô tả trong objective.', difficulty: index > 2 ? 'medium' : 'easy', recommendedType: item.objectiveType === 'procedure_execution' ? 'sorting' : item.objectiveType === 'consultation_skill' || item.objectiveType === 'objection_handling' ? 'scenario_choice' : 'multiple_choice' }))
  const coverage = { totalSections: request.document.sections.length, usedSections: request.document.sections.length, skippedSections: 0, reviewSections: classifications.filter((item) => item.confidence === 'low').length, percentage: request.document.sections.length ? 100 : 0, coverageViewed: false, omitted: [] }
  const graphBase = { contentMap: classifications, instructionalUnits: units }; const salesRelevance = calculateSalesRelevance(graphBase)
  const warnings = [{ id: instructionalId('warning'), code: 'rule_based_analysis', message: 'Rule-based analysis — không phải AI provider thật.', important: true, sourceReferences: [], resolution: 'open' as const }, ...request.document.detectedSignals.filter((item) => ['price', 'promotion', 'campaign', 'campaign_rule'].includes(item)).map((signal) => ({ id: instructionalId('warning'), code: `verify_${signal}`, message: `Nội dung ${signal} có thể thay đổi; Trainer cần xác minh.`, important: true, sourceReferences: refs, resolution: 'open' as const }))]
  const assumptions = [...(!request.audience.trim() ? [{ id: instructionalId('assumption'), statement: 'Đối tượng học được suy đoán là nhân viên bán hàng.', affectedItemIds: learningObjectives.map((item) => item.id), reason: 'Audience không được cung cấp.', requiresTrainerVerification: true }] : [])]
  return { schemaVersion: 1, id: instructionalId('graph'), sourceDocumentId: request.document.sourceId, titleSuggestion: request.document.metadata.title, audience: request.audience, trainingContext: request.trainingContext, overallLearningGoal: request.trainerGoal?.trim() || 'Áp dụng kiến thức nguồn vào tư vấn khách hàng nhất quán tại cửa hàng.', learningObjectives, contentMap: classifications, instructionalUnits: units, assessmentPlan: { enabled: request.includeAssessment, objectiveCoverage: learningObjectives.length ? 100 : 0, recommendedQuestionCount: Math.max(3, Math.min(10, learningObjectives.length * 2)), recommendedQuestionTypes: [...new Set(candidates.map((item) => item.recommendedType))], difficultyDistribution: { easy: 60, medium: 30, hard: 10 }, mustTestTopics: learningObjectives.filter((item) => item.priority === 'must').map((item) => item.statement), scenarioBasedCandidates: candidates.filter((item) => item.recommendedType === 'scenario_choice'), complianceQuestions: candidates.filter((_, index) => classifications[index]?.type === 'Campaign Condition'), warnings: [] }, retailApplicationPlan: ['Thực hành một tình huống tư vấn tại quầy.', 'Dùng checklist để tự đánh giá sau ca học.'], sourceCoverage: coverage, salesRelevance, warnings, assumptions, confidence: request.document.qualityScore >= 80 ? 'medium' : 'low', confidenceReason: request.document.qualityScore < 80 ? 'Document quality dưới 80%.' : 'Rule-based output cần Trainer review.', createdAt: timestamp, updatedAt: timestamp, reviewStatus: 'unreviewed', goalReviewed: false, provider: 'rule_based', model: 'deterministic-v1', generatedAt: timestamp, analysisType: 'rule_based', status: 'needs_review' }
}

function reference(document: DocumentHandoff, section: DocumentHandoff['sections'][number]): SourceReference { const element = section.elements[0]; return { documentId: document.sourceId, sectionId: section.id, elementId: element?.id, excerpt: excerpt(element?.content || section.title), confidence: element ? 'high' : 'low' } }
function classify(signals: RetailSignal[]): ClassificationType { for (const signal of signals) { const mapped = retailSignalToClassification[signal]; if (mapped) return mapped } return 'Reference Only' }
function objective(title: string, type: ClassificationType, sourceReference: SourceReference): LearningObjective { const mapping: Partial<Record<ClassificationType, [LearningObjective['objectiveType'], LearningObjective['bloomLevel'], string]>> = { 'Sales Objection': ['objection_handling', 'apply', 'Xử lý'], 'Consultation Scenario': ['consultation_skill', 'apply', 'Áp dụng'], 'Campaign Condition': ['campaign_compliance', 'apply', 'Xác định'], Procedure: ['procedure_execution', 'apply', 'Thực hiện'], 'Customer Need': ['consultation_skill', 'analyze', 'Phân tích'], 'Product Specification': ['knowledge', 'understand', 'Phân biệt'] }; const [objectiveType, bloomLevel, verb] = mapping[type] ?? ['application', 'apply', 'Giải thích']; return { id: instructionalId('objective'), statement: `${verb} ${title.toLocaleLowerCase('vi')} trong bối cảnh tư vấn tại cửa hàng.`, objectiveType, bloomLevel, priority: 'must', sourceReferences: [sourceReference], confidence: type === 'Reference Only' ? 'low' : 'medium', confidenceReason: type === 'Reference Only' ? 'Section chưa có classification mạnh.' : undefined, reviewStatus: 'unreviewed' } }
function formatFor(type: ClassificationType): RecommendedFormat { if (type === 'Sales Objection' || type === 'Consultation Scenario') return 'scenario'; if (type === 'Procedure') return 'sorting'; if (type === 'Campaign Condition' || type === 'Warning') return 'quick_question'; if (type === 'Product Specification') return 'comparison'; if (type === 'FAQ') return 'flashcard'; if (type === 'Apply at Store') return 'store_practice'; return 'explanation' }
const purposeFor = (type: ClassificationType) => `Chuyển ${type} thành hành vi học tập có thể áp dụng.`
const interactionRationale = (type: ClassificationType) => type === 'Procedure' ? 'Sắp xếp giúp luyện đúng thứ tự.' : type.includes('Scenario') || type === 'Sales Objection' ? 'Scenario giúp luyện quyết định tư vấn.' : 'Tương tác ngắn giúp kiểm tra hiểu biết.'
const sequenceRationale = (type: ClassificationType, index: number) => index === 0 ? 'Mở đầu bằng lý do nội dung quan trọng.' : type === 'Consultation Scenario' || type === 'Sales Objection' ? 'Đặt sau kiến thức nền để áp dụng vào khách hàng.' : 'Tăng dần từ kiến thức đến ứng dụng.'
const excerpt = (value: string) => value.trim().replace(/\s+/g, ' ').slice(0, 180)
