import { instructionalId } from './instructionalFixtures'
import type { InstructionalGraph, LearningObjective, ObjectivePriority, RecommendedFormat } from './instructionalGraph'

export const editObjective = (graph: InstructionalGraph, objectiveId: string, statement: string): InstructionalGraph => ({ ...graph, learningObjectives: graph.learningObjectives.map((item) => item.id === objectiveId ? { ...item, statement, reviewStatus: 'unreviewed' } : item), updatedAt: new Date().toISOString() })
export const deleteObjective = (graph: InstructionalGraph, objectiveId: string): InstructionalGraph => ({ ...graph, learningObjectives: graph.learningObjectives.filter((item) => item.id !== objectiveId), instructionalUnits: graph.instructionalUnits.map((unit) => ({ ...unit, linkedObjectives: unit.linkedObjectives.filter((id) => id !== objectiveId) })), updatedAt: new Date().toISOString() })
export const addObjective = (graph: InstructionalGraph, statement = 'Objective mới cần Trainer hoàn thiện.'): InstructionalGraph => { const reference = graph.instructionalUnits[0]?.sourceReferences[0]; const objective: LearningObjective = { id: instructionalId('objective-manual'), statement, objectiveType: 'application', bloomLevel: 'apply', priority: 'should', sourceReferences: reference ? [reference] : [], confidence: 'low', confidenceReason: 'Trainer thêm thủ công.', reviewStatus: 'unreviewed' }; return { ...graph, learningObjectives: [...graph.learningObjectives, objective], updatedAt: new Date().toISOString() } }
export const setObjectivePriority = (graph: InstructionalGraph, objectiveId: string, priority: ObjectivePriority): InstructionalGraph => ({ ...graph, learningObjectives: graph.learningObjectives.map((item) => item.id === objectiveId ? { ...item, priority } : item), updatedAt: new Date().toISOString() })
export const markObjectiveReviewed = (graph: InstructionalGraph, objectiveId: string): InstructionalGraph => ({ ...graph, learningObjectives: graph.learningObjectives.map((item) => item.id === objectiveId ? { ...item, reviewStatus: 'reviewed' } : item), updatedAt: new Date().toISOString() })
export function reorderUnit(graph: InstructionalGraph, unitId: string, delta: number): InstructionalGraph { const ordered = [...graph.instructionalUnits].sort((a, b) => a.sequenceIndex - b.sequenceIndex); const index = ordered.findIndex((item) => item.id === unitId); const target = index + delta; if (index < 0 || target < 0 || target >= ordered.length) return graph; [ordered[index], ordered[target]] = [ordered[target]!, ordered[index]!]; return { ...graph, instructionalUnits: ordered.map((item, position) => ({ ...item, sequenceIndex: position + 1, reviewStatus: item.id === unitId ? 'unreviewed' : item.reviewStatus })), updatedAt: new Date().toISOString() } }
export const setUnitFormat = (graph: InstructionalGraph, unitId: string, format: RecommendedFormat): InstructionalGraph => ({ ...graph, instructionalUnits: graph.instructionalUnits.map((item) => item.id === unitId ? { ...item, recommendedFormat: format, reviewStatus: 'unreviewed' } : item), updatedAt: new Date().toISOString() })
export const markUnitReviewed = (graph: InstructionalGraph, unitId: string): InstructionalGraph => ({ ...graph, instructionalUnits: graph.instructionalUnits.map((item) => item.id === unitId ? { ...item, reviewStatus: 'reviewed' } : item), updatedAt: new Date().toISOString() })
export const resolveInstructionalWarning = (graph: InstructionalGraph, warningId: string): InstructionalGraph => ({ ...graph, warnings: graph.warnings.map((item) => item.id === warningId ? { ...item, resolution: 'resolved' } : item), updatedAt: new Date().toISOString() })
export const dismissInstructionalWarning = (graph: InstructionalGraph, warningId: string, reason: string): InstructionalGraph => ({ ...graph, warnings: graph.warnings.map((item) => item.id === warningId ? { ...item, resolution: 'dismissed', dismissReason: reason } : item), updatedAt: new Date().toISOString() })
