import type { ClassificationType, InstructionalGraph, InstructionalValidation, RecommendedFormat } from './instructionalGraph'

const classifications = new Set<ClassificationType>(['Product Knowledge', 'Product Specification', 'Customer Need', 'Customer Benefit', 'Key Selling Point', 'Sales Objection', 'Consultation Scenario', 'Campaign Condition', 'Policy', 'Procedure', 'Common Mistake', 'FAQ', 'Warning', 'Trainer Note', 'Apply at Store', 'Assessment Candidate', 'Reference Only'])
const formats = new Set<RecommendedFormat>(['explanation', 'comparison', 'checklist', 'walkthrough', 'scenario', 'flashcard', 'quick_question', 'quiz', 'sorting', 'matching', 'image_explanation', 'video_explanation', 'store_practice'])
export function validateInstructionalGraph(graph: InstructionalGraph): InstructionalValidation {
  const errors: InstructionalValidation['errors'] = []; const warnings: InstructionalValidation['warnings'] = []
  if (!graph.overallLearningGoal.trim()) errors.push(issue('goal', 'overallLearningGoal', 'Cần overall learning goal.'))
  if (!graph.learningObjectives.length) errors.push(issue('objectives', 'learningObjectives', 'Cần ít nhất một learning objective.'))
  graph.learningObjectives.forEach((objective, index) => { if (!objective.statement.trim()) errors.push(issue(`objective-${objective.id}`, `learningObjectives.${index}`, 'Objective không được rỗng.')); if (!objective.sourceReferences.length) errors.push(issue(`objective-source-${objective.id}`, `learningObjectives.${index}.sourceReferences`, 'Objective cần source reference.')); if (/^hiểu\b|^biết\b/i.test(objective.statement)) warnings.push(issue(`objective-general-${objective.id}`, `learningObjectives.${index}`, 'Objective quá chung; cần hành vi quan sát được.')); if (!/phân biệt|xác định|áp dụng|thực hiện|tư vấn|giải thích|đánh giá|nhận diện/i.test(objective.statement)) warnings.push(issue(`objective-application-${objective.id}`, `learningObjectives.${index}`, 'Objective thiếu hành vi ứng dụng rõ ràng.')) })
  if (!graph.instructionalUnits.length) errors.push(issue('units', 'instructionalUnits', 'Cần ít nhất một instructional unit.'))
  const sequence = new Set<number>(); const objectiveIds = new Set(graph.learningObjectives.map((item) => item.id))
  graph.instructionalUnits.forEach((unit, index) => { if (!unit.sourceReferences.length) errors.push(issue(`unit-source-${unit.id}`, `instructionalUnits.${index}`, 'Instructional unit cần source reference.')); if (sequence.has(unit.sequenceIndex) || unit.sequenceIndex < 1) errors.push(issue(`unit-sequence-${unit.id}`, `instructionalUnits.${index}.sequenceIndex`, 'Sequence index trùng hoặc không hợp lệ.')); sequence.add(unit.sequenceIndex); if (!formats.has(unit.recommendedFormat)) errors.push(issue(`unit-format-${unit.id}`, `instructionalUnits.${index}.recommendedFormat`, 'Recommended format không được hỗ trợ.')); if (unit.estimatedDuration > 15 || unit.conceptCount > 5 || unit.cognitiveLoad === 'high') warnings.push(issue(`unit-load-${unit.id}`, `instructionalUnits.${index}`, 'Unit có cognitive load cao hoặc quá dài.')); if (!unit.suggestedInteractions.length) warnings.push(issue(`unit-interaction-${unit.id}`, `instructionalUnits.${index}`, 'Unit thiếu tương tác đề xuất.')) })
  graph.contentMap.forEach((item, index) => { if (!classifications.has(item.type)) errors.push(issue(`classification-${item.id}`, `contentMap.${index}.type`, 'Classification không được hỗ trợ.')); if (!item.sourceReferences.length) errors.push(issue(`classification-source-${item.id}`, `contentMap.${index}.sourceReferences`, 'Classification cần source reference.')) })
  graph.assessmentPlan.scenarioBasedCandidates.concat(graph.assessmentPlan.complianceQuestions).forEach((candidate) => { if (!objectiveIds.has(candidate.objectiveId)) errors.push(issue(`assessment-${candidate.id}`, 'assessmentPlan', 'Assessment candidate không có objective hợp lệ.')); if (!candidate.sourceReferences.length) errors.push(issue(`assessment-source-${candidate.id}`, 'assessmentPlan', 'Assessment candidate cần source reference.')) })
  if (graph.sourceCoverage.percentage < 50) warnings.push(issue('coverage-low', 'sourceCoverage', 'Source coverage thấp.'))
  if (graph.confidence === 'low' || graph.learningObjectives.some((item) => item.confidence === 'low') || graph.instructionalUnits.some((item) => item.confidence === 'low')) warnings.push(issue('confidence-low', 'confidence', 'Có item confidence thấp cần Trainer xác minh.'))
  if (!graph.salesRelevance.metrics.find((item) => item.id === 'scenario')?.passed) warnings.push(issue('sales-scenario', 'salesRelevance', 'Thiếu consultation scenario.'))
  if (!graph.salesRelevance.metrics.find((item) => item.id === 'objection')?.passed) warnings.push(issue('sales-objection', 'salesRelevance', 'Thiếu objection handling.'))
  return { errors, warnings }
}
const issue = (id: string, path: string, message: string) => ({ id, path, message })
