import type { DocumentHandoff, RetailSignal } from '../../document/types'

export type InstructionalConfidence = 'high' | 'medium' | 'low'
export type InstructionalReviewStatus = 'unreviewed' | 'reviewed' | 'needs_changes' | 'approved'
export type ObjectiveType = 'knowledge' | 'comprehension' | 'application' | 'consultation_skill' | 'objection_handling' | 'procedure_execution' | 'campaign_compliance'
export type BloomLevel = 'remember' | 'understand' | 'apply' | 'analyze'
export type ObjectivePriority = 'must' | 'should' | 'could'
export type ClassificationType = 'Product Knowledge' | 'Product Specification' | 'Customer Need' | 'Customer Benefit' | 'Key Selling Point' | 'Sales Objection' | 'Consultation Scenario' | 'Campaign Condition' | 'Policy' | 'Procedure' | 'Common Mistake' | 'FAQ' | 'Warning' | 'Trainer Note' | 'Apply at Store' | 'Assessment Candidate' | 'Reference Only'
export type RecommendedFormat = 'explanation' | 'comparison' | 'checklist' | 'walkthrough' | 'scenario' | 'flashcard' | 'quick_question' | 'quiz' | 'sorting' | 'matching' | 'image_explanation' | 'video_explanation' | 'store_practice'
export type AssessmentType = 'multiple_choice' | 'true_false' | 'multiple_select' | 'scenario_choice' | 'sorting' | 'matching'

export interface SourceReference { documentId: string; page?: number; slide?: number; sectionId: string; elementId?: string; excerpt: string; confidence: InstructionalConfidence }
export interface LearningObjective { id: string; statement: string; objectiveType: ObjectiveType; bloomLevel: BloomLevel; priority: ObjectivePriority; sourceReferences: SourceReference[]; confidence: InstructionalConfidence; confidenceReason?: string; reviewStatus: InstructionalReviewStatus }
export interface ContentClassification { id: string; type: ClassificationType; confidence: InstructionalConfidence; reason: string; sourceReferences: SourceReference[] }
export interface InteractionRecommendation { format: RecommendedFormat; rationale: string; sourceReferences: SourceReference[] }
export interface InstructionalUnit { id: string; proposedTitle: string; purpose: string; linkedObjectives: string[]; sourceReferences: SourceReference[]; contentClassification: ClassificationType[]; recommendedFormat: RecommendedFormat; estimatedDuration: number; estimatedReadingLoad: 'light' | 'moderate' | 'heavy'; conceptCount: number; cognitiveLoad: 'low' | 'medium' | 'high'; difficulty: 'basic' | 'intermediate' | 'advanced'; prerequisites: string[]; keyMessages: Array<{ text: string; sourceReferences: SourceReference[] }>; customerBenefits: string[]; commonMistakes: string[]; salesApplications: string[]; suggestedInteractions: InteractionRecommendation[]; warnings: string[]; confidence: InstructionalConfidence; confidenceReason?: string; reviewStatus: InstructionalReviewStatus; sequenceIndex: number; sequenceRationale: string; dependencyIds: string[] }
export interface AssessmentCandidate { id: string; objectiveId: string; sourceReferences: SourceReference[]; rationale: string; difficulty: 'easy' | 'medium' | 'hard'; recommendedType: AssessmentType }
export interface AssessmentPlan { enabled: boolean; objectiveCoverage: number; recommendedQuestionCount: number; recommendedQuestionTypes: AssessmentType[]; difficultyDistribution: { easy: number; medium: number; hard: number }; mustTestTopics: string[]; scenarioBasedCandidates: AssessmentCandidate[]; complianceQuestions: AssessmentCandidate[]; warnings: string[] }
export interface SourceCoverage { totalSections: number; usedSections: number; skippedSections: number; reviewSections: number; percentage: number; coverageViewed: boolean; omitted: Array<{ sectionId: string; title: string; reason: 'duplicate' | 'reference only' | 'unsupported' | 'insufficient context' | 'irrelevant' | 'outdated candidate' | 'needs trainer verification' }> }
export interface SalesMetric { id: string; label: string; passed: boolean; reason: string }
export interface SalesRelevanceSummary { metrics: SalesMetric[]; missingSalesElements: string[] }
export interface InstructionalWarning { id: string; code: string; message: string; important: boolean; sourceReferences: SourceReference[]; resolution: 'open' | 'resolved' | 'dismissed'; dismissReason?: string }
export interface InstructionalAssumption { id: string; statement: string; affectedItemIds: string[]; reason: string; requiresTrainerVerification: boolean }
export interface InstructionalGraph {
  schemaVersion: 1; id: string; sourceDocumentId: string; sourceDocumentVersion?: number; parentGraphId?: string; titleSuggestion: string; audience: string; trainingContext: string; overallLearningGoal: string; learningObjectives: LearningObjective[]; contentMap: ContentClassification[]; instructionalUnits: InstructionalUnit[]; assessmentPlan: AssessmentPlan; retailApplicationPlan: string[]; sourceCoverage: SourceCoverage; salesRelevance: SalesRelevanceSummary; warnings: InstructionalWarning[]; assumptions: InstructionalAssumption[]; confidence: InstructionalConfidence; confidenceReason?: string; createdAt: string; updatedAt: string; reviewStatus: InstructionalReviewStatus; goalReviewed: boolean; provider: string; model: string; generatedAt: string; analysisType: 'ai' | 'rule_based'; status: 'ready' | 'needs_review' | 'approved' | 'archived'
}
export interface InstructionalAnalysisRequest { document: DocumentHandoff; courseType: 'product' | 'sales' | 'campaign'; audience: string; trainingContext: string; desiredLearningDuration: number; desiredLessonLength: 'short' | 'medium'; includeAssessment: boolean; retailContext: string; sourceLanguage: 'vi' | 'en'; outputLanguage: 'vi' | 'en'; trainerGoal?: string; requestId: string }
export interface InstructionalAnalysisResponse { requestId: string; graph: InstructionalGraph; provider: string; model: string; generatedAt: string; latencyMs: number; analysisType: 'ai' | 'rule_based'; warnings: string[] }
export interface InstructionalValidationIssue { id: string; path: string; message: string }
export interface InstructionalValidation { errors: InstructionalValidationIssue[]; warnings: InstructionalValidationIssue[] }
export const retailSignalToClassification: Partial<Record<RetailSignal, ClassificationType>> = { product: 'Product Knowledge', specification: 'Product Specification', scenario: 'Consultation Scenario', campaign: 'Campaign Condition', campaign_rule: 'Campaign Condition', faq: 'FAQ', warning: 'Warning', price: 'Sales Objection', promotion: 'Campaign Condition', trainer_note: 'Trainer Note' }
