import { ArrowLeft, ChevronDown, ChevronUp, Copy, Eye, Plus, Save, Send, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, useBlocker, useNavigate, useParams } from 'react-router-dom'
import { BlockEditor } from '../../components/admin/BlockEditor'
import { ImportExportPanel } from '../../components/admin/ImportExportPanel'
import { QuizEditor } from '../../components/admin/QuizEditor'
import { LessonBlockRenderer } from '../../components/lesson/LessonBlockRenderer'
import { useContent } from '../../context/ContentContext'
import { contentService, createCourse, createLesson, createModule, validateCourseForPublish, type PublishValidationIssue } from '../../services/contentService'
import { ConfirmDialog } from '../../components/admin/ConfirmDialog'
import type { BadgeCondition, Course, Module } from '../../types'

type Tab = 'settings' | 'structure' | 'lesson' | 'quiz' | 'rewards' | 'preview' | 'transfer'
const tabLabels: Record<Tab, string> = { settings: 'Cài đặt', structure: 'Modules & Lessons', lesson: 'Lesson Editor', quiz: 'Quiz', rewards: 'XP & Badge', preview: 'Preview', transfer: 'Import / Export' }
const uid = (prefix: string) => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}`
function move<T>(items: T[], index: number, delta: number) { const target = index + delta; if (target < 0 || target >= items.length) return items; const next = [...items]; [next[index], next[target]] = [next[target], next[index]]; return next }

export function CourseEditorPage() {
  const { courseId } = useParams(); const isNew = !courseId; const { refresh } = useContent(); const navigate = useNavigate()
  const initial = useMemo(() => courseId ? contentService.getCourse(courseId, 'trainer') : createCourse(), [courseId]); const [course, setCourse] = useState<Course | null>(initial ?? null); const [savedSnapshot, setSavedSnapshot] = useState(() => JSON.stringify(initial)); const [tab, setTab] = useState<Tab>('settings'); const [selected, setSelected] = useState<{ moduleId: string; lessonId: string } | null>(null); const [notice, setNotice] = useState(''); const [issues, setIssues] = useState<PublishValidationIssue[]>([])
  const dirty = JSON.stringify(course) !== savedSnapshot
  const blocker = useBlocker(({ currentLocation, nextLocation }) => dirty && currentLocation.pathname !== nextLocation.pathname)
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault() }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn) }, [dirty])
  if (!course) return <section className="system-page"><h1>Không tìm thấy khóa học</h1><Link to="/admin/courses">Về danh sách</Link></section>
  const updateModule = (moduleId: string, updater: (module: Module) => Module) => setCourse({ ...course, modules: course.modules.map((module) => module.id === moduleId ? updater(module) : module) })
  const selectedModule = course.modules.find((module) => module.id === selected?.moduleId); const selectedLesson = selectedModule?.lessons.find((lesson) => lesson.id === selected?.lessonId)
  const save = () => { if (!course.title.trim()) { setNotice('Tên khóa học là bắt buộc.'); return } if (isNew && !contentService.getCourse(course.id, 'trainer')) contentService.addCourse(course); else contentService.updateCourse(course); refresh(); setSavedSnapshot(JSON.stringify(course)); setNotice('Đã lưu vào trình duyệt.'); if (isNew) navigate(`/admin/courses/${course.id}/edit`, { replace: true }) }
  const focusIssue = (issue: PublishValidationIssue) => { setTab(issue.tab); if (issue.moduleId && issue.lessonId) setSelected({ moduleId: issue.moduleId, lessonId: issue.lessonId }) }
  const publish = () => { const nextIssues = validateCourseForPublish(course); setIssues(nextIssues); if (nextIssues.length) { setNotice(`Chưa thể publish: còn ${nextIssues.length} lỗi cần xử lý.`); focusIssue(nextIssues[0]); return } const next = { ...course, publishStatus: 'published' as const }; setCourse(next); contentService.updateCourse(next); refresh(); setSavedSnapshot(JSON.stringify(next)); setNotice('Đã publish. Employee có thể học khóa này ngay.') }
  return <section className="course-builder"><ConfirmDialog open={blocker.state === 'blocked'} title="Rời Course Builder?" description="Bạn có thay đổi chưa lưu. Nếu rời trang, các thay đổi này sẽ bị mất." confirmLabel="Rời trang" onCancel={() => blocker.reset?.()} onConfirm={() => blocker.proceed?.()} /><div className="builder-topbar"><Link to="/admin/courses"><ArrowLeft />Danh sách</Link><div><span className={`badge ${course.publishStatus === 'published' ? 'badge-success' : 'badge-warning'}`}>{course.publishStatus}</span><strong>{course.title}</strong><small className={dirty ? 'save-state dirty' : 'save-state'}>{dirty ? 'Có thay đổi chưa lưu' : `Đã lưu · ${new Date(course.updatedAt).toLocaleString('vi-VN')}`}</small></div><div><button className="button button-secondary" onClick={save}><Save />Lưu</button><button className="button button-primary" onClick={publish}><Send />Publish</button></div></div>{notice && <p className="builder-notice" role="status">{notice}</p>}{issues.length > 0 && <section className="validation-panel" role="alert"><strong>Kiểm tra trước khi publish</strong><ul>{issues.map((issue) => <li key={issue.id}><button onClick={() => focusIssue(issue)}>{issue.message}</button></li>)}</ul></section>}<nav className="builder-tabs" aria-label="Course Builder">{(Object.keys(tabLabels) as Tab[]).map((item) => <button aria-current={tab === item ? 'page' : undefined} className={tab === item ? 'active' : ''} onClick={() => setTab(item)} key={item}>{tabLabels[item]}</button>)}</nav>
    {tab === 'settings' && <div className="builder-panel form-grid"><label className="cms-field full"><span>Tên khóa học</span><input value={course.title} onChange={(event) => setCourse({ ...course, title: event.target.value })} /></label><label className="cms-field full"><span>Mô tả</span><textarea value={course.description} onChange={(event) => setCourse({ ...course, description: event.target.value })} /></label><label className="cms-field"><span>Ảnh bìa URL</span><input value={course.coverUrl} onChange={(event) => setCourse({ ...course, coverUrl: event.target.value })} /></label><label className="cms-field"><span>Màu chủ đạo</span><input type="color" value={course.accentColor} onChange={(event) => setCourse({ ...course, accentColor: event.target.value })} /></label><label className="cms-field"><span>Thời lượng dự kiến</span><input type="number" value={course.durationMinutes} onChange={(event) => setCourse({ ...course, durationMinutes: Number(event.target.value) })} /></label><label className="cms-field"><span>Danh mục</span><input value={course.category} onChange={(event) => setCourse({ ...course, category: event.target.value })} /></label><label className="cms-field full"><span>Mục tiêu — mỗi dòng một mục</span><textarea value={course.objectives.join('\n')} onChange={(event) => setCourse({ ...course, objectives: event.target.value.split('\n').filter(Boolean) })} /></label></div>}
    {tab === 'structure' && <div className="builder-panel"><div className="section-heading compact"><div><span className="overline">Outline</span><h2>Cấu trúc khóa học</h2></div><button className="button button-primary" onClick={() => setCourse({ ...course, modules: [...course.modules, createModule()] })}><Plus />Thêm module</button></div>{course.modules.map((module, moduleIndex) => <article className="outline-module" key={module.id}><header><input aria-label="Tên module" value={module.title} onChange={(event) => updateModule(module.id, (item) => ({ ...item, title: event.target.value }))} /><span><button aria-label="Di chuyển module lên" onClick={() => setCourse({ ...course, modules: move(course.modules, moduleIndex, -1) })}><ChevronUp /></button><button aria-label="Di chuyển module xuống" onClick={() => setCourse({ ...course, modules: move(course.modules, moduleIndex, 1) })}><ChevronDown /></button><button aria-label="Xóa module" onClick={() => setCourse({ ...course, modules: course.modules.filter((item) => item.id !== module.id) })}><Trash2 /></button></span></header>{module.lessons.map((lesson, lessonIndex) => <div className="outline-lesson" key={lesson.id}><button className="lesson-edit-link" onClick={() => { setSelected({ moduleId: module.id, lessonId: lesson.id }); setTab('lesson') }}><Eye />{lesson.title}</button><label><input type="checkbox" checked={lesson.required} onChange={(event) => updateModule(module.id, (item) => ({ ...item, lessons: item.lessons.map((value) => value.id === lesson.id ? { ...value, required: event.target.checked } : value) }))} />Bắt buộc</label><span><button aria-label="Di chuyển lesson lên" onClick={() => updateModule(module.id, (item) => ({ ...item, lessons: move(item.lessons, lessonIndex, -1) }))}><ChevronUp /></button><button aria-label="Di chuyển lesson xuống" onClick={() => updateModule(module.id, (item) => ({ ...item, lessons: move(item.lessons, lessonIndex, 1) }))}><ChevronDown /></button><button aria-label="Duplicate lesson" onClick={() => updateModule(module.id, (item) => ({ ...item, lessons: [...item.lessons.slice(0, lessonIndex + 1), { ...structuredClone(lesson), id: uid('lesson'), title: `${lesson.title} (Bản sao)` }, ...item.lessons.slice(lessonIndex + 1)] }))}><Copy /></button><button aria-label="Xóa lesson" onClick={() => updateModule(module.id, (item) => ({ ...item, lessons: item.lessons.filter((value) => value.id !== lesson.id) }))}><Trash2 /></button></span></div>)}<button className="add-outline" onClick={() => updateModule(module.id, (item) => ({ ...item, lessons: [...item.lessons, createLesson()] }))}><Plus />Thêm lesson</button></article>)}</div>}
    {tab === 'lesson' && <div className="builder-panel">{selectedLesson && selectedModule ? <><div className="form-grid lesson-settings"><label className="cms-field full"><span>Tên lesson</span><input value={selectedLesson.title} onChange={(event) => updateModule(selectedModule.id, (module) => ({ ...module, lessons: module.lessons.map((lesson) => lesson.id === selectedLesson.id ? { ...lesson, title: event.target.value } : lesson) }))} /></label><label className="cms-field"><span>Thời lượng</span><input type="number" value={selectedLesson.durationMinutes} onChange={(event) => updateModule(selectedModule.id, (module) => ({ ...module, lessons: module.lessons.map((lesson) => lesson.id === selectedLesson.id ? { ...lesson, durationMinutes: Number(event.target.value) } : lesson) }))} /></label><label className="cms-field"><span>XP hoàn thành lesson</span><input type="number" value={selectedLesson.xpReward} onChange={(event) => updateModule(selectedModule.id, (module) => ({ ...module, lessons: module.lessons.map((lesson) => lesson.id === selectedLesson.id ? { ...lesson, xpReward: Number(event.target.value) } : lesson) }))} /></label></div><BlockEditor blocks={selectedLesson.blocks} onChange={(blocks) => updateModule(selectedModule.id, (module) => ({ ...module, lessons: module.lessons.map((lesson) => lesson.id === selectedLesson.id ? { ...lesson, blocks } : lesson) }))} /><details className="lesson-preview-full"><summary><Eye />Preview toàn bài</summary><article className="lesson-article preview-surface"><h1>{selectedLesson.title}</h1>{selectedLesson.blocks.map((block) => <LessonBlockRenderer key={block.id} block={block} />)}</article></details></> : <div className="empty-product-state"><h2>Chọn một lesson</h2><p>Mở tab Modules & Lessons và chọn lesson cần chỉnh sửa.</p><button className="button button-primary" onClick={() => setTab('structure')}>Mở cấu trúc</button></div>}</div>}
    {tab === 'quiz' && <div className="builder-panel"><QuizEditor quiz={course.quiz} onChange={(quiz) => setCourse({ ...course, quiz })} /></div>}
    {tab === 'rewards' && <div className="builder-panel"><div className="form-grid"><label className="cms-field"><span>XP hoàn thành course</span><input type="number" value={course.gamification.courseCompletionXp} onChange={(event) => setCourse({ ...course, gamification: { ...course.gamification, courseCompletionXp: Number(event.target.value) } })} /></label></div><div className="section-heading compact"><div><h2>Badge</h2><p>Badge mẫu theo điều kiện học tập.</p></div><button className="button button-primary" onClick={() => setCourse({ ...course, gamification: { ...course.gamification, badges: [...course.gamification.badges, { id: uid('badge'), name: 'Badge mới', description: '', condition: 'first_lesson' }] } })}><Plus />Thêm badge</button></div>{course.gamification.badges.map((badge) => <div className="badge-editor" key={badge.id}><input aria-label="Tên badge" value={badge.name} onChange={(event) => setCourse({ ...course, gamification: { ...course.gamification, badges: course.gamification.badges.map((item) => item.id === badge.id ? { ...item, name: event.target.value } : item) } })} /><input aria-label="Mô tả badge" value={badge.description} onChange={(event) => setCourse({ ...course, gamification: { ...course.gamification, badges: course.gamification.badges.map((item) => item.id === badge.id ? { ...item, description: event.target.value } : item) } })} /><select aria-label="Điều kiện badge" value={badge.condition} onChange={(event) => setCourse({ ...course, gamification: { ...course.gamification, badges: course.gamification.badges.map((item) => item.id === badge.id ? { ...item, condition: event.target.value as BadgeCondition } : item) } })}><option value="first_lesson">Hoàn thành bài đầu tiên</option><option value="module_complete">Hoàn thành module</option><option value="quiz_passed">Đạt quiz</option><option value="course_complete">Hoàn thành khóa học</option></select><button aria-label="Xóa badge" onClick={() => setCourse({ ...course, gamification: { ...course.gamification, badges: course.gamification.badges.filter((item) => item.id !== badge.id) } })}><Trash2 /></button></div>)}</div>}
    {tab === 'preview' && <div className="builder-panel course-preview"><span className="overline">Preview dùng Employee renderer</span><h1>{course.title}</h1><p>{course.description}</p>{course.modules.map((module) => <section key={module.id}><h2>{module.title}</h2>{module.lessons.map((lesson) => <details key={lesson.id}><summary>{lesson.title}</summary><article className="lesson-article preview-surface">{lesson.blocks.map((block) => <LessonBlockRenderer key={block.id} block={block} />)}</article></details>)}</section>)}</div>}
    {tab === 'transfer' && <div className="builder-panel"><ImportExportPanel courseId={isNew ? undefined : course.id} onChange={() => { refresh(); setNotice('Content store đã được cập nhật.'); }} /></div>}
  </section>
}
